export const meta = {
  name: 'chain',
  description: 'Evidence review chain',
  whenToUse: 'A finished object needs a review where no executable oracle decides: a diff, a document, a plan. Aspect critics hint, facts settle the hints, one judge accepts, one fixer changes.',
  phases: [{ title: 'Critique' }, { title: 'Evidence' }, { title: 'Triage' }, { title: 'Fix' }],
}
/* usage:
Evidence review chain: aspect critics, grouped hints, facts, judge, one fix round.
in (array of absolute paths, required)
ask (string, what changed, what to judge, required)
out (string, absolute path, required)
aspects (array, required, from: simplicity reliability security extensibility performance scalability testability operability data-integrity cost)
depth (string lite std full, default std)
base (string, control-run version, default HEAD)
test (string, one shell line)
class (string c1-c5, default c3)
submodes (array: no-sonnet no-opus no-fable, default [])
size (string small medium large, default medium)
Out: accepted, rejected, undetermined rows in out; put the returned undetermined list to the user.
Use: review where no oracle decides. Not: authoring.
*/

// ---- shared block (generated by bin/build.sh from lib/block.src.js; never edit here) ----
// Shared script block. Source of truth: lib/block.src.js plus lib/classes.json; edit those only.
// bin/build.sh renders them into lib/block.js and stamps lib/block.js between the shared-block
// markers of every target named by lib/build-manifest.json. lib/block.js and every stamped copy
// are generated: a hand edit inside them is lost at the next build and fails `bin/build.sh --check`.
// Scripts cannot import, so every workflow carries a byte-identical copy of this block.
// Pure functions only: no file access, no harness global (`args`, `agent`, `log`), no side effect.

// ---- class table ----
const CLASSES = {
  "defaultClass": "c3",
  "slots": [
    "main",
    "opus",
    "sonnet"
  ],
  "slotDown": {
    "main": "opus",
    "opus": "sonnet",
    "sonnet": "sonnet"
  },
  "sizes": [
    "small",
    "medium",
    "large"
  ],
  "defaultSize": "medium",
  "models": {
    "fab": "fable",
    "ops": "opus",
    "son": "sonnet"
  },
  "efforts": {
    "lo": "low",
    "me": "medium",
    "hi": "high"
  },
  "submodeOrder": [
    "no-sonnet",
    "no-opus",
    "no-fable"
  ],
  "submodeKeys": [
    "none",
    "no-sonnet",
    "no-opus",
    "no-fable",
    "no-sonnet no-opus",
    "no-sonnet no-fable",
    "no-opus no-fable"
  ],
  "table": {
    "c1": {
      "none": "ops-lo/ops-lo/son-lo",
      "no-sonnet": "ops-lo/ops-lo/ops-lo",
      "no-opus": "son-me/son-me/son-lo",
      "no-fable": "ops-lo/ops-lo/son-lo",
      "no-sonnet no-opus": "fab-lo/fab-lo/fab-lo",
      "no-sonnet no-fable": "ops-lo/ops-lo/ops-lo",
      "no-opus no-fable": "son-me/son-me/son-lo"
    },
    "c2": {
      "none": "fab-lo/ops-lo/son-me",
      "no-sonnet": "fab-lo/ops-lo/ops-lo",
      "no-opus": "fab-lo/son-me/son-me",
      "no-fable": "ops-me/ops-lo/son-me",
      "no-sonnet no-opus": "fab-lo/fab-lo/fab-lo",
      "no-sonnet no-fable": "ops-me/ops-lo/ops-lo",
      "no-opus no-fable": "son-me/son-me/son-me"
    },
    "c3": {
      "none": "fab-lo/ops-me/son-hi",
      "no-sonnet": "fab-lo/ops-me/ops-me",
      "no-opus": "fab-lo/son-hi/son-hi",
      "no-fable": "ops-me/ops-me/son-hi",
      "no-sonnet no-opus": "fab-lo/fab-lo/fab-lo",
      "no-sonnet no-fable": "ops-me/ops-me/ops-me",
      "no-opus no-fable": "son-me/son-hi/son-hi"
    },
    "c4": {
      "none": "fab-me/ops-hi/son-hi",
      "no-sonnet": "fab-me/ops-hi/ops-me",
      "no-opus": "fab-me/fab-me/son-hi",
      "no-fable": "ops-hi/ops-hi/son-hi",
      "no-sonnet no-opus": "fab-me/fab-me/fab-lo",
      "no-sonnet no-fable": "ops-hi/ops-hi/ops-me",
      "no-opus no-fable": "son-hi/son-hi/son-hi"
    },
    "c5": {
      "none": "fab-hi/ops-hi/ops-hi",
      "no-sonnet": "fab-hi/ops-hi/ops-hi",
      "no-opus": "fab-hi/fab-me/fab-me",
      "no-fable": "ops-hi/ops-hi/ops-hi",
      "no-sonnet no-opus": "fab-hi/fab-me/fab-me",
      "no-sonnet no-fable": "ops-hi/ops-hi/ops-hi",
      "no-opus no-fable": "son-hi/son-hi/son-hi"
    }
  },
  "classStep": {
    "c1": "c2",
    "c2": "c3",
    "c3": "c4",
    "c4": "c5",
    "c5": "c5"
  },
  "roles": {
    "plan-author": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": true
    },
    "spec-author": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": true
    },
    "scenario-author": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": true
    },
    "code-author": {
      "agent": "tools-edit",
      "slot": "sonnet",
      "uplift": false
    },
    "test-author": {
      "agent": "tools-edit",
      "slot": "sonnet",
      "uplift": false
    },
    "coverage-checker": {
      "agent": "tools-read-write",
      "slot": "sonnet",
      "uplift": false
    },
    "critic": {
      "agent": "tools-read-write",
      "slot": "main",
      "splitSlot": "opus",
      "uplift": false
    },
    "evidence-researcher": {
      "agent": "tools-read-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "evidence": {
      "agent": "tools-read-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "evidence-triage": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": false
    },
    "fixer": {
      "agent": "tools-edit",
      "slot": "opus",
      "uplift": false
    },
    "researcher": {
      "agent": "tools-read-write-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "web-researcher": {
      "agent": "tools-web",
      "slot": "sonnet",
      "uplift": false
    },
    "synthesizer": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": true
    },
    "executor": {
      "agent": "tools-read-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "waiter": {
      "agent": "tools-read-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "translator": {
      "agent": "tools-read-write",
      "slot": "opus",
      "uplift": false
    }
  },
  "ceilings": {
    "lite": {
      "agents": 2,
      "cycles": 1
    },
    "std": {
      "agents": 5,
      "cycles": 2
    },
    "full": {
      "agents": 10,
      "cycles": 3
    }
  }
}
// ---- end class table ----

const MODEL_NAME = CLASSES.models
const EFFORT_NAME = CLASSES.efforts

// submodes(list) -> { subs, key }: submodes in the table's order, the row key of the class table.
function submodes(list) {
  const given = list || []
  const bad = given.filter(s => !CLASSES.submodeOrder.includes(s))
  if (bad.length) throw new Error(`unknown submode ${bad.join(' ')}`)
  const subs = CLASSES.submodeOrder.filter(s => given.includes(s))
  if (subs.length === 3) throw new Error('all three submodes banned: nothing left to run on')
  return { subs, key: subs.join(' ') || 'none' }
}

// cellFor(class, submodes) -> { main, opus, sonnet }, each the short cell of the class table.
function cellFor(cls, subs) {
  const row = CLASSES.table[cls]
  if (!row) throw new Error(`unknown class ${cls}`)
  const parts = row[submodes(subs).key].split('/')
  return { main: parts[0], opus: parts[1], sonnet: parts[2] }
}

// optsFor(class, submodes, slot, job) -> { model, effort, label } for one agent() call.
function optsFor(cls, subs, slot, job, extra) {
  const cell = cellFor(cls, subs)
  if (!Object.prototype.hasOwnProperty.call(cell, slot)) throw new Error(`unknown slot ${slot}`)
  const short = cell[slot]
  const m = short.split('-')[0]
  const e = short.split('-')[1]
  // `extra` spreads first: a call site adds keys (agentType, tools) but never overrides the model,
  // the effort or the label, which only the class table decides.
  return { ...(extra || {}), model: MODEL_NAME[m], effort: EFFORT_NAME[e], label: `${short}-${job}` }
}

// classUp(class): the one class step of 3.5 rule 2 and rule 3; the top class steps to itself.
function classUp(cls) {
  const next = CLASSES.classStep[cls]
  if (!next) throw new Error(`unknown class ${cls}`)
  return next
}

// slotForSize(slot, size): a large input moves a role one slot down, never up, never past the
// cheapest slot (A32; the launcher states the volume, a script cannot measure its inputs).
function slotForSize(slot, size) {
  if (!CLASSES.slots.includes(slot)) throw new Error(`unknown slot ${slot}`)
  const s = size || CLASSES.defaultSize
  if (!CLASSES.sizes.includes(s)) throw new Error(`unknown size ${s}`)
  return s === 'large' ? CLASSES.slotDown[slot] : slot
}

// bindClass(class, submodes): the class of one run; every stage asks it for its agent options.
function bindClass(cls, subs) {
  const s = submodes(subs)
  const cell = cellFor(cls, s.subs)
  return {
    class: cls,
    submodes: s.subs,
    cell,
    name: stem => [cls, ...s.subs, stem].join('-'),
    opts: (slot, job, extra) => optsFor(cls, s.subs, slot, job, extra),
    up: () => bindClass(classUp(cls), s.subs),
  }
}

// roleOf / roleAgent / roleSlot / roleClass: the per-role slot map of lib/classes.json.
function roleOf(name) {
  const r = CLASSES.roles[name]
  if (!r) throw new Error(`unknown role ${name}`)
  return r
}
function roleNames() { return Object.keys(CLASSES.roles) }
function roleAgent(name) { return roleOf(name).agent }
function roleSlot(name, size, split) {
  const r = roleOf(name)
  return slotForSize(split && r.splitSlot ? r.splitSlot : r.slot, size)
}
// roleClass(role, class): an output no oracle can check gets a stronger author, one class step up.
function roleClass(name, cls) { return roleOf(name).uplift ? classUp(cls) : cls }

// ceiling(depth) -> { agents, cycles } (A30); ceilingHit is true when `used` units reach the
// ceiling, so the next unit may not start: the stage ends and writes the gap.
function ceiling(depth) {
  const c = CLASSES.ceilings[depth]
  if (!c) throw new Error(`unknown depth ${depth}`)
  return c
}
function ceilingHit(depth, kind, used) {
  const c = ceiling(depth)
  if (!Object.prototype.hasOwnProperty.call(c, kind)) throw new Error(`unknown ceiling ${kind}`)
  const n = Number(used)
  // a NaN would compare false and let the ceiling pass unnoticed: a bad counter is an error.
  if (!Number.isFinite(n)) throw new Error(`ceilingHit needs a number of ${kind}, got ${used}`)
  return n >= c[kind]
}

// isBlocked / lastLine: the return shape every tool-set agent keeps. Every agent file puts the
// blocked word on the LAST line, so only that line counts: a return quoting the word mid-text
// (a finding, a file path, an error string) is a normal return, not a blocked stage.
function lastLine(ret) { return String(ret == null ? '' : ret).trim().split('\n').pop() }
function isBlocked(ret) { return ret == null || /^BLOCKED:/.test(lastLine(ret).trim()) }

// blockedLine(why): the blocked value of a stage, carrying the block word exactly once. Reasons
// come from two sources: an agent return that already opens with the word, and a reason this block
// wrote itself; prefixing both would print the word twice.
function blockedLine(why) {
  const w = String(why == null ? '' : why).trim() || 'no reason'
  return /^BLOCKED:/.test(w) ? w : `BLOCKED: ${w}`
}

// mustExist(ret, out): the output check of every stage that names an output file. A workflow
// script has no file access, so the agent's own return is the evidence: it names the path it
// wrote. Returns { ok, out, reason }; a false ok stops the flow instead of feeding the next stage.
function mustExist(ret, out) {
  if (!out) throw new Error('mustExist needs the output path')
  const s = String(ret == null ? '' : ret)
  // the agent's own last line is the reason, unprefixed here: blockedLine puts the word on once
  if (isBlocked(ret)) return { ok: false, out, reason: lastLine(s) || 'no return' }
  if (s.indexOf(out) === -1) return { ok: false, out, reason: `return does not name ${out}` }
  return { ok: true, out }
}

// outVerdict(ret, out): the whole verdict of a stage that names an output file — mustExist plus
// the size the agent reports. A script has no file access, so that number is the only evidence the
// file is not empty: a missing or zero count is an empty output, and an empty output is blocked,
// never done. The count counts only on a line naming the output path, and only on the FIRST such
// line, the demanded one: a later line naming the path with a byte count (a quoted run log, a
// check output, another file) must not decide the stage.
function outVerdict(ret, out) {
  const m = mustExist(ret, out)
  if (!m.ok) return { ok: false, out, bytes: 0, reason: m.reason, blocked: blockedLine(m.reason) }
  const RE = /(\d[\d,]*) *bytes\b/
  const line = String(ret).split('\n').filter(l => l.indexOf(out) !== -1 && RE.test(l))[0] || ''
  const n = Number(((line.match(RE) || [])[1] || '').replace(/,/g, ''))
  if (!(n > 0)) {
    const why = `return reports no non-empty ${out}: no positive byte count on a line naming it`
    return { ok: false, out, bytes: 0, reason: why, blocked: blockedLine(why) }
  }
  return { ok: true, out, bytes: n }
}

// ---- the review chain of idea 3.6 ----
// Every decision of the chain lives here as a pure function over the returns of its stages, so a
// test executes it instead of grepping workflows/chain.js. A workflow script has no file access:
// the hint lists and the evidence answers reach the script only as lines of an agent return, which
// is why the two parsers below are part of the chain and not of the prompt.

const HINT_CAP = 5 // A27: at most 5 hints per critic, so N critics give at most 5 x N hints
const SEVERITY_ORDER = ['low', 'medium', 'high']
const EVIDENCE_VERDICTS = ['confirmed', 'refuted', 'undetermined', 'harness']

// keyedFields(text, tag, width): the lines of an agent return that carry one keyed answer, split
// into their fields. A real return decorates its answers the way an agent writes everything else:
// a list marker, a blockquote or a heading before the tag, backticks or bold around the tag, a
// lowercase tag, a colon or a dash where the first `|` belongs, prose lines before and after, and
// a long answer wrapped onto a second line. None of that changes the answer, so it is stripped.
// Nothing else is guessed: a line without the tag is prose and binds nothing, and a field that is
// absent stays absent — which every caller below reads as "settled by nobody".
// `width` is how many fields a whole answer has; only a row still short of that many takes the
// next prose line as its continuation, so a finished answer is never extended by the text after
// it. A wrap inside the last field of a whole row is therefore cut at the wrap: the role texts
// ask for one line per answer, and swallowing the prose after a complete row would be worse.
const LEAD = /^[ \t]*(?:[-*+>][ \t]+|#{1,6}[ \t]+|\d+[.)][ \t]+)*/
const TAG_DECOR = '[`*_]*'
const WORD_DECOR = /^[`*_"']+|[`*_"'.,;]+$/g
// word(s): a short field — an id, a verdict, a severity, the control-run flag — with its
// decoration removed. The prose fields keep theirs: only the keys the flow reads are normalised.
const word = s => String(s == null ? '' : s).trim().replace(WORD_DECOR, '').trim()
function keyedFields(text, tag, width) {
  const head = new RegExp(`^${TAG_DECOR}${tag}${TAG_DECOR}[ \\t]*[|:\\u2013\\u2014-][ \\t]*`, 'i')
  const n = Number(width || 0)
  const rows = []
  for (const line of String(text == null ? '' : text).split('\n')) {
    const s = String(line).replace(LEAD, '').trim()
    if (!s) continue
    if (head.test(s)) { rows.push(s.replace(head, '').split('|').map(x => x.trim())); continue }
    const last = rows[rows.length - 1]
    if (!last || last.length >= n) continue
    const add = s.split('|').map(x => x.trim())
    last[last.length - 1] = `${last[last.length - 1]} ${add[0]}`.trim()
    for (const x of add.slice(1)) last.push(x)
  }
  return rows
}

// placeOf(place): "file:12-30", "file:12" or "doc.md#Section"; anything else is the whole file.
function placeOf(place) {
  const s = String(place == null ? '' : place).trim()
  const hash = s.indexOf('#')
  if (hash !== -1) {
    return { file: s.slice(0, hash).trim(), section: s.slice(hash + 1).trim(), from: null, to: null }
  }
  const m = s.match(/^(.*?):(\d+)(?:\s*-\s*(\d+))?$/)
  if (m) return { file: m[1].trim(), section: null, from: Number(m[2]), to: Number(m[3] || m[2]) }
  return { file: s, section: null, from: null, to: null }
}

// placeText(p): the place of a group, written back in the form the critics use.
function placeText(p) {
  if (p.section) return `${p.file}#${p.section}`
  if (p.from == null) return p.file
  return `${p.file}:${p.from}-${p.to}`
}

// parseHints(text, aspect): the hint lines of one critic return. Format, one line per hint:
//   HINT | <aspect> | <place> | <severity> | <suspected error> | <evidence that would settle it>
// Everything else in the return is prose and is ignored; a hint with no place could not be
// grouped and could not be settled, so it is no hint. The decoration a real critic writes around
// such a line is read through keyedFields().
function parseHints(text, aspect) {
  const hints = []
  for (const f of keyedFields(text, 'HINT', 5)) {
    const place = word(f[1] || '')
    if (!place) continue
    const sev = word(f[2] || '').toLowerCase()
    hints.push({
      aspect: word(f[0] || '') || aspect || '',
      place,
      ...placeOf(place),
      // an unreadable severity counts as medium: it must not silently become the highest one and
      // pull the whole run into the long form
      severity: SEVERITY_ORDER.includes(sev) ? sev : 'medium',
      what: f[3] || '',
      evidence: f.slice(4).join(' | '),
    })
  }
  return hints
}

// capHints(hints, cap): the cap of A27, applied per critic. The critic writes the strongest first,
// so the cap keeps the head of its list.
function capHints(hintList, cap) {
  const n = Number(cap == null ? HINT_CAP : cap)
  if (!Number.isFinite(n) || n < 1) throw new Error(`capHints needs a positive cap, got ${cap}`)
  const hints = hintList || []
  return hints.slice(0, n)
}

// hintsOverlap(a, b): same place. Two line ranges overlap when they intersect; a hint on a whole
// file covers every hint in that file; a document section meets only the same section.
function hintsOverlap(a, b) {
  if (a.file !== b.file) return false
  if (a.section || b.section) return a.section === b.section
  if (a.from == null || b.from == null) return true
  return a.from <= b.to && b.from <= a.to
}

function higher(x, y) {
  return SEVERITY_ORDER.indexOf(x) >= SEVERITY_ORDER.indexOf(y) ? x : y
}

function joinInto(g, h) {
  g.from = g.from == null || h.from == null ? null : Math.min(g.from, h.from)
  g.to = g.from == null || h.to == null ? null : Math.max(g.to, h.to)
  g.severity = higher(g.severity, h.severity)
  for (const a of h.aspects || [h.aspect]) if (a && !g.aspects.includes(a)) g.aspects.push(a)
  g.hints = g.hints.concat(h.hints || [h])
  g.place = placeText(g)
  return g
}

// groupHints(hints): the merge and dedupe of 3.6, in the script and with no extra agent. Hints on
// the same or overlapping place form one group that keeps all its aspect tags and the highest
// severity of its members, so two critics pointing at the same lines cost one evidence run, not
// two. Same-meaning hints on different places stay separate.
function groupHints(hints) {
  const groups = []
  for (const h of hints || []) {
    const hit = groups.filter(g => hintsOverlap(g, h))
    if (!hit.length) {
      groups.push({
        file: h.file, section: h.section, from: h.from, to: h.to, place: h.place,
        severity: h.severity, aspects: h.aspect ? [h.aspect] : [], hints: [h],
      })
      continue
    }
    const g = joinInto(hit[0], h)
    // a later hint can bridge two groups that did not meet before: they become one
    for (const other of hit.slice(1)) {
      joinInto(g, other)
      groups.splice(groups.indexOf(other), 1)
    }
  }
  // every hint carries an id of its own inside its group (`g1.h2`). A group is one evidence run,
  // but the answers are per hint: a group holding a confirmed hint and a refuted one must not
  // carry the refuted one to the fixer under the group's verdict (A28).
  return groups.map((g, i) => {
    const id = `g${i + 1}`
    return {
      ...g, aspects: g.aspects.slice().sort(), id,
      hints: (g.hints || []).map((h, j) => ({ ...h, id: `${id}.h${j + 1}` })),
    }
  })
}

// maxSeverity(groups): the severity of the whole critique, the second input of the form choice.
function maxSeverity(groups) {
  let top = null
  for (const g of groups || []) top = top == null ? g.severity : higher(top, g.severity)
  return top
}

// chainForm(depth, maxSeverity): idea decision 5. The long form (one evidence researcher per
// group, then a separate triage) for `full` and for any hint group of high severity; the short
// form (one agent that collects and decides in one pass) otherwise.
function chainForm(depth, sev) {
  if (!CLASSES.ceilings[depth]) throw new Error(`unknown depth ${depth}`)
  return depth === 'full' || sev === 'high' ? 'long' : 'short'
}

// pickAspects(names, catalog): the `aspects` argument against the static catalog. It selects
// paragraphs and carries no prompt text; an unknown name is returned to the launcher, and the
// workflow stops instead of running a critic with no aspect paragraph.
function pickAspects(names, catalog) {
  const known = Array.isArray(catalog) ? catalog.slice() : Object.keys(catalog || {})
  const given = (names || []).slice()
  return { names: given, unknown: given.filter(n => !known.includes(n)), known }
}

// criticSplit(depth, names): one merged critic at `lite` and whenever a single aspect is asked
// for; one critic per aspect above that (3.6, A5). The split also decides the slot: a split
// critic sits one slot down, through roleSlot(name, size, split).
function criticSplit(depth, names) {
  if (!CLASSES.ceilings[depth]) throw new Error(`unknown depth ${depth}`)
  const list = (names || []).slice()
  if (depth === 'lite' || list.length < 2) return [list]
  return list.map(n => [n])
}

// parseEvidence(text): the answer lines of an evidence stage. Format, one line per hint group:
//   EVIDENCE | <group id> | confirmed|refuted|undetermined|harness | base:yes|base:no | <pointer>
// An unreadable verdict counts as undetermined: it then goes to the user and never to the fixer.
function parseEvidence(text) {
  const answers = []
  for (const f of keyedFields(text, 'EVIDENCE', 4)) {
    // the id of an answer is a hint id (`g1.h2`); the group it belongs to is its head
    const id = word(f[0] || '')
    if (!id) continue
    const group = id.split('.')[0]
    const v = word(f[1] || '').toLowerCase()
    let verdict = EVIDENCE_VERDICTS.includes(v) ? v : 'undetermined'
    const base = word(f[2] || '')
    // a missing or unreadable control-run field settles nothing: reading it as `base:no` would
    // turn an answer nobody controlled into a finding of this change. It goes to the user, the
    // same way an unreadable verdict does. A harness failure needs no control run.
    if (verdict !== 'harness' && !/^base:\s*(yes|no)$/i.test(base)) verdict = 'undetermined'
    answers.push({
      id,
      group,
      verdict,
      kind: verdict === 'harness' ? 'harness' : 'object',
      onBase: /^base:\s*yes$/i.test(base),
      pointer: f.slice(3).join(' | '),
    })
  }
  return answers
}

// splitFailures(answers): the two rules of 3.6 that keep a finding honest. A failure of our own
// harness (tool, access, sandbox) is no finding about the object and is kept in its own list; a
// failure that also reproduces on the base version is no finding of this change either.
// Only a settled answer can be closed by the control run: an `undetermined` row with `base:yes`
// was settled by nobody, so it stays among the findings, reaches the undetermined list and the
// user (A28), and is never closed as "no finding of this change".
// dedupeAnswers(answers): one answer per hint. A stage that wrote two lines for one hint would
// otherwise put that hint in two lists at once — confirmed to the fixer and undetermined to
// the user. The stronger evidence wins: a settled verdict beats an unsettled one and beats a
// failure of our own harness; two settled verdicts that contradict each other (confirmed and
// refuted) settle nothing, so the hint goes to the user as undetermined.
const ANSWER_RANK = ['harness', 'undetermined', 'refuted', 'confirmed']
function dedupeAnswers(answers) {
  const out = []
  for (const a of answers || []) {
    const cur = out.filter(x => x.id === a.id)[0]
    if (!cur) { out.push({ ...a }); continue }
    const settled = v => v === 'confirmed' || v === 'refuted'
    const i = out.indexOf(cur)
    if (settled(cur.verdict) && settled(a.verdict) && cur.verdict !== a.verdict) {
      out[i] = { ...cur, verdict: 'undetermined', kind: 'object', pointer: `${cur.pointer} ;; ${a.pointer}` }
    } else if (ANSWER_RANK.indexOf(a.verdict) > ANSWER_RANK.indexOf(cur.verdict)) {
      out[i] = { ...a }
    }
  }
  return out
}

function splitFailures(answers) {
  const all = dedupeAnswers(answers)
  const harness = all.filter(a => a.kind === 'harness')
  const rest = all.filter(a => a.kind !== 'harness')
  const closed = a => a.onBase && a.verdict !== 'undetermined'
  const onBase = rest.filter(a => closed(a))
  const findings = rest.filter(a => !closed(a))
  return { findings, harness, onBase }
}

// hintRows(groups, answers): every hint of every group that ran, bound to the answer that settled
// it. The binding lives here and nowhere else, so the fixer's mandate, the review file and the
// return read the same rows and can no longer tell two different stories (A28).
// An answer names a hint id (`g1.h2`). A group of one hint is that hint, so an answer naming the
// group settles it; a group of several hints is not — one verdict over several hints would carry
// the refuted and the unsettled hints to the fixer under the confirmed one. A hint no answer
// names is unanswered: nothing settled it, so it is undetermined, never confirmed.
function hintRows(groups, answers) {
  const all = dedupeAnswers(answers)
  const kindOf = a => a.kind === 'harness'
    ? 'harness'
    : (a.onBase && a.verdict !== 'undetermined' ? 'onBase' : 'finding')
  const rows = []
  for (const g of groups || []) {
    const hints = (g.hints || []).length ? g.hints : [{ id: g.id, place: g.place, what: '' }]
    for (const h of hints) {
      const byHint = all.filter(x => x.id === h.id)[0]
      const byGroup = hints.length === 1 ? all.filter(x => x.id === g.id)[0] : null
      const a = byHint || byGroup || null
      rows.push({
        id: h.id, group: g.id, place: h.place || g.place, what: h.what || '',
        answered: !!a, verdict: a ? a.verdict : 'undetermined',
        kind: a ? kindOf(a) : 'finding', pointer: a ? a.pointer : '',
      })
    }
  }
  return rows
}

// chainRows(groups, answers): the one table of a chain run. The result file the judge writes and
// the return the caller reads are both this table — the open rows above all (A28), so a run can
// no longer return `undetermined: []` while its review file holds unsettled rows.
function chainRows(groups, answers) {
  const rows = hintRows(groups, answers)
  const findings = rows.filter(r => r.kind === 'finding')
  const undetermined = findings.filter(r => r.answered && r.verdict === 'undetermined')
  const unanswered = findings.filter(r => !r.answered)
  return {
    rows,
    findings,
    confirmed: findings.filter(r => r.verdict === 'confirmed'),
    rejected: findings.filter(r => r.verdict === 'refuted'),
    undetermined,
    unanswered,
    open: undetermined.concat(unanswered),
    harness: rows.filter(r => r.kind === 'harness'),
    onBase: rows.filter(r => r.kind === 'onBase'),
  }
}

// openRowsText(rows): the unsettled section of the review file, rendered from the rows the return
// carries. The judge copies this block instead of composing a list of its own.
function openRowsText(rows) {
  const open = (rows && rows.open) || []
  if (!open.length) return '(none)'
  return open.map(r => `| ${r.id} | ${r.place} | ${r.answered ? r.pointer || 'the facts settle nothing' : 'the evidence run came back with no readable answer for this hint'} |`).join('\n')
}

// fixerInput(groups, answers): what may reach the one who changes the object. A hint without
// evidence changes nothing, so a group goes on with its confirmed hints only; refuted,
// undetermined, harness, base-version and unanswered hints all stay out (A28).
function fixerInput(groups, answers) {
  const ok = chainRows(groups, answers).confirmed.map(r => r.id)
  const out = []
  for (const g of groups || []) {
    const hints = (g.hints || []).filter(h => ok.includes(h.id))
    if (hints.length) { out.push({ ...g, hints }); continue }
    // a group that carries no hint list of its own is addressed by its group id
    if (!(g.hints || []).length && ok.includes(g.id)) out.push(g)
  }
  return out
}

// confirmedOf(groups, answers): the hints a fact confirmed. The `confirmed` count of the result
// and of the status is this one, never the count that reached the fixer: a run whose triage or fix
// stage blocked still confirmed what it confirmed, and a judge that rejected a confirmed hint does
// not unmake the fact (A28). What the fixer got is its own number.
function confirmedOf(groups, answers) {
  return chainRows(groups, answers).confirmed
}

// undeterminedOf(groups, answers): the list that goes into the result file and into the status,
// for the main session to put to the user (A28: a script has no place for the user).
function undeterminedOf(groups, answers) {
  return chainRows(groups, answers).undetermined
}

// unansweredOf(groups, answers): a hint that ran and came back with no readable answer line.
// Nothing settled it, so it is neither confirmed nor rejected: it goes to the user with the
// undetermined ones (A28). Counting it out of existence would drop a whole hint.
function unansweredOf(groups, answers) {
  return chainRows(groups, answers).unanswered
}

// parseAccepted(text): the accepted rows of the judge's return. Format, one line per row:
//   ACCEPTED | <hint id> | <the change in one sentence>
// The whole decision stands in the judge's result file; these lines are the part a script without
// file access can read, and they are the only mandate the fixer gets.
function parseAccepted(text) {
  const rows = []
  for (const f of keyedFields(text, 'ACCEPTED', 2)) {
    const id = word(f[0] || '')
    if (!id) continue
    rows.push({ id, group: id.split('.')[0], change: f.slice(1).join(' | ') })
  }
  return rows
}

// judgedInput(groups, answers, rows): the fixer's mandate in the long form. The judge decides
// which hints become changes, so a hint it rejected or left unsettled never reaches the fixer;
// it cannot widen the mandate either, so a row no fact confirmed stays out (A28). No accepted
// row, no fix stage.
function judgedInput(groups, answers, rows) {
  const ids = (rows || []).map(r => r.id)
  const out = []
  for (const g of fixerInput(groups, answers)) {
    const hints = (g.hints || []).filter(h => ids.includes(h.id))
    if (hints.length) { out.push({ ...g, hints }); continue }
    if (!(g.hints || []).length && ids.includes(g.id)) out.push(g)
  }
  return out
}

// chainSeats(depth, wanted): the ceiling of A30 is a ceiling per stage — at most `agents` units
// in one stage. What does not fit never starts: the stage ends and the rest becomes the gap of
// the result, never a second round. `seats` is what starts, `gap` what never does: a caller needs
// no third number, so none is returned.
function chainSeats(depth, wanted) {
  const room = ceiling(depth).agents
  const n = Number(wanted)
  if (!Number.isFinite(n) || n < 0) throw new Error(`chainSeats needs a unit count, got ${wanted}`)
  const seats = Math.min(n, room)
  return { room, seats, gap: n - seats }
}

// aspectsOrStop(names, catalog): the gate of the `aspects` argument. An unknown name selects no
// paragraph, so the critic would run with no question at all: the run stops and the catalog goes
// back to the launcher (3.6). An empty list is no review either.
function aspectsOrStop(names, catalog) {
  const p = pickAspects(names, catalog)
  if (!p.names.length) {
    return { ok: false, known: p.known, why: blockedLine('args.aspects must name at least one catalog aspect') }
  }
  if (p.unknown.length) {
    return { ok: false, known: p.known, why: blockedLine(`unknown aspect ${p.unknown.join(' ')}`) }
  }
  return { ok: true, known: p.known, names: p.names, why: null }
}

// chainPlan(depth, names, catalog): the whole plan of the critic stage as one decision — the gate
// of the `aspects` argument, the split into critic sets (A5) and the ceiling of A30 over them.
// `ok:false` stops the run before any agent starts and hands `why` and the catalog back to the
// launcher; `sets` are the critics that start, `gap` the ones the ceiling left out (never a second
// round), and `split` is the slot flag: a split critic sits one slot down.
function chainPlan(depth, names, catalog) {
  const gate = aspectsOrStop(names, catalog)
  if (!gate.ok) return { ok: false, known: gate.known, why: gate.why, sets: [], gap: [], room: 0, split: false }
  const all = criticSplit(depth, gate.names)
  const seats = chainSeats(depth, all.length)
  return {
    ok: true, known: gate.known, why: null,
    sets: all.slice(0, seats.seats), gap: all.slice(seats.seats),
    room: seats.room, split: all.length > 1,
  }
}

// chainEvidenceRuns(depth, form, groups): the groups the evidence stage really starts, the highest
// severity first, and the groups the ceiling of A30 left as the gap. The short form is one agent
// for every group, so it cuts nothing; the long form is one agent per group and takes the seats.
function chainEvidenceRuns(depth, form, groups) {
  const ordered = (groups || []).slice()
    .sort((a, b) => SEVERITY_ORDER.indexOf(b.severity) - SEVERITY_ORDER.indexOf(a.severity))
  if (form !== 'long') return { room: ceiling(depth).agents, ran: ordered, gap: [] }
  const seats = chainSeats(depth, ordered.length)
  return { room: seats.room, ran: ordered.slice(0, seats.seats), gap: ordered.slice(seats.seats) }
}

// chainStatus(s): the status sentence of one chain run, the one place that states the A28
// contract — the open rows go to the user, and the chain ran one round.
function chainStatus(s) {
  const o = s || {}
  const open = Number(o.undetermined || 0) + Number(o.unanswered || 0)
  const where = o.out || 'the result file'
  const openText = open
    ? `The ${open} open row(s) stand in ${where} and in this return: put them to the user, one decision each, before anything else is changed.`
    : 'Nothing is open for the user.'
  const gap = Number(o.gap || 0)
  const gapText = gap
    ? ` ${gap} unit(s) never started: the ceiling of ${Number(o.room || 0)} agents per stage ended the stage.`
    : ''
  // two numbers, never one: `confirmed` counts the facts, `to the fixer` counts the groups the
  // fix stage really got. A blocked triage reports the facts it has and 0 to the fixer.
  return `${o.form} form, ${Number(o.groups || 0)} hint group(s), ${Number(o.confirmed || 0)} confirmed, ${Number(o.fixing || 0)} to the fixer, ${open} open. ${openText}${gapText} One round only: a second critique needs the user's word.`
}

// chainResult(s): the whole return of one chain run, built in one place, so a stage that blocks
// late returns what the run already knows instead of a bare blocked line: the undetermined rows,
// the groups nobody answered, the harness failures in their own list, the failures that reproduce
// on the base version (named), the evidence files written, the gap and the status sentence (A28).
// `groups` is every group of the run, `ran` the groups a stage really started.
function chainResult(s) {
  const o = s || {}
  const groups = o.groups || []
  const answers = o.answers || []
  // one table for the whole run: the return and the review file are rendered from these same rows
  const T = chainRows(o.ran || groups, answers)
  // the facts are counted from the answers themselves, so no caller can claim a confirmation the
  // evidence never gave, and a stage that blocked late still reports what was confirmed
  const conf = T.confirmed
  const und = T.undetermined
  const open = T.unanswered
  const base = o.base || 'the base version'
  const res = {
    out: o.out == null ? null : o.out,
    form: o.form,
    aspects: o.aspects || [],
    critics: Number(o.critics || 0),
    groups: groups.length,
    confirmed: conf.length,
    fixing: Number(o.fixing || 0),
    fixed: o.fixed || 'no accepted row: nothing was changed',
    undetermined: und.map(r => `${r.id}: ${r.place} — ${r.pointer}`),
    unanswered: open.map(r => `${r.id} at ${r.place}: the stage ran and came back with no readable answer`),
    harness: T.harness.map(r => `${r.id}: ${r.pointer}`),
    onBase: T.onBase.map(r => `${r.id}: reproduces on ${base}, no finding of this change`),
    evidence: o.evidence || [],
    gap: o.gap || [],
    blockedStages: o.blockedStages || [],
    status: chainStatus({
      form: o.form, groups: groups.length, confirmed: conf.length, fixing: Number(o.fixing || 0),
      undetermined: und.length, unanswered: open.length, out: o.out,
      gap: Number(o.gapCount || 0), room: Number(o.room || 0),
    }),
  }
  if (o.stage) res.stage = o.stage
  if (o.blocked) res.blocked = blockedLine(o.blocked)
  return res
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    CLASSES, MODEL_NAME, EFFORT_NAME, submodes, cellFor, optsFor, classUp, slotForSize, bindClass,
    roleOf, roleNames, roleAgent, roleSlot, roleClass, ceiling, ceilingHit, isBlocked, lastLine,
    blockedLine, mustExist, outVerdict,
    HINT_CAP, SEVERITY_ORDER, keyedFields, placeOf, placeText, parseHints, capHints, hintsOverlap, groupHints,
    maxSeverity, chainForm, pickAspects, criticSplit, parseEvidence, dedupeAnswers, splitFailures,
    hintRows, chainRows, openRowsText,
    fixerInput, confirmedOf, undeterminedOf, unansweredOf, parseAccepted, judgedInput, chainSeats,
    aspectsOrStop, chainPlan, chainEvidenceRuns, chainStatus, chainResult,
  }
}
// ---- end shared block ----

// ---- roles (generated by bin/build.sh from lib/roles/*.md; never edit here) ----
const ROLE_TEXT = {
  "critic": "Critic. You read the object below in a clean context and point at the places where an error may hide. You give hints, never verdicts: what you suspect is settled later by facts, not by your confidence.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nTool-call budget: at most 12 calls, and no call that changes anything. Read the object, then stop reading and write. Spending the budget on a wide tour costs more than it finds; read what the task points at.\n\nAt most 5 hints, the strongest first. Every hint carries: the aspect it comes from; the place (file and line range, or document section); the error you suspect, in one sentence; the severity (high, medium, low); and the one piece of evidence that would settle it \u2014 a command to run, a file to read, a value to compare. A hint nobody could settle is not a hint, drop it.\n\nNo praise, no summary of what the object does, no style remark, no restatement of a rule the object already follows. When the task names a version from before the change, a shape that already stands in it is no finding of this change: hint at what this change brought.\n\nWrite the hint list into `{out}` in that shape and change nothing else.\n\nReturn: the output path and the hint count by severity, then the hints themselves \u2014 one line per hint, nothing else on the line:\n\n`HINT | reliability | slug.js:4 | high | the cut can land on a dash and leave a trailing one | run slug('ab cd', 3) and look at the tail`\n\nOnly those lines are read: a hint that stands in `{out}` but on no line of your return is a hint nobody got, and a count is no hint. Then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "evidence-researcher": "Evidence researcher. One group of hints, many cheap queries, one answer per hint: confirmed, refuted or undetermined. You decide nothing about what to change; you bring the facts that decide it.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nFor every hint of the group, one answer under that hint's own id: run the check the hint names, read the code path around the place, and reproduce the failure when the hint claims one. A failure, or a shape, that already stands in the unchanged base version is not a finding of this change \u2014 say so, with both runs or both places quoted.\n\nAnswer each hint with `confirmed`, `refuted` or `undetermined`, every answer carrying its pointer: file and line, command and its decisive output line, or commit hash. `confirmed` needs a fact of the object that holds this one hint up; a hint the files and the runs neither hold up nor settle is `undetermined`, never `confirmed`, and no hint is confirmed for sounding right. `undetermined` is a real answer and better than a guess; it says what you tried and what would settle it.\n\nA hint that calls something needless, duplicated or absent is refuted as soon as a fact stands against it: a caller, a test, or a rule of the object's own documents that needs exactly that thing. Look for one before you confirm such a hint, and quote it with file and line.\n\nKeep two kinds of failure apart: a failure of the object under review, and a failure of your own run (a tool, an access, a sandbox limit). The second one is never a finding about the object; report it in its own list.\n\nWrite the answers into `{out}` and change nothing under review. You have no Write tool: create `{out}` with a shell redirect, and write no other file.\n\nReturn: the output path and the counts (confirmed, refuted, undetermined, harness failures), then your answers themselves \u2014 one line per hint id, nothing else on the line:\n\n`EVIDENCE | g1.h2 | refuted | base:no | check.js:2 calls slug(s, 12), so the argument the hint calls needless has a caller`\n\nEvery hint id of your group gets its own such line, in that order of fields. Only those lines are read: a count, a summary, and one verdict written over a whole group settle no hint and reach nobody, and an answer that stands in `{out}` but on no line of your return is an answer nobody got. Then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "evidence": "Evidence agent, short form: you collect the facts for the hints below and decide each one yourself, in one pass.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nPer hint, under that hint's own id: run the check it names, read the place it points at, then say `confirmed` (a fact of the object holds this one hint up and it names a real change), `refuted` (a fact settles it against the hint) or `undetermined` (the facts do not settle it, so it goes to the user). Every line carries its pointer: file and line, command with its decisive output line, or commit hash. A claim with no pointer does not go in, and a hint nothing holds up is `undetermined`, never `confirmed`.\n\nA hint that calls something needless, duplicated or absent is refuted as soon as a caller, a test or a rule of the object's own documents needs exactly that thing; look for one before you confirm such a hint.\n\nA failure, or a shape, that already stands in the unchanged base version is not a finding of this change. A failure of your own run \u2014 tool, access, sandbox \u2014 is `harness`, no finding about the object either; keep those in their own list.\n\nA confirmed hint states the change in one sentence: what to change and where. It never states how to write the code.\n\nYou have no Write tool: create `{out}` with a shell redirect, and write no other file. Write the same four words into `{out}`: confirmed with the change, refuted with the refuting fact, undetermined with what is missing, harness failures apart.\n\nReturn: the output path and the four counts, then your answers themselves \u2014 one line per hint id, nothing else on the line:\n\n`EVIDENCE | g1.h2 | refuted | base:no | check.js:2 calls slug(s, 12), so the argument the hint calls needless has a caller`\n\nEvery hint id you were given gets its own such line, in that order of fields. Only those lines are read: a count, a summary, and one verdict written over a whole group settle no hint and reach nobody, and an answer that stands in the file but on no line of your return is an answer nobody got. Then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "evidence-triage": "Triage. You are the judge of the review: you read the hints and the facts collected for them, and you decide which ones become changes. You run no query of your own \u2014 if a decision needs a fact nobody collected, that hint is unsettled, and unsettled goes to the user, never to the one who changes the object.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nPer hint, by its own id: accept it only when its own row of the fact list says `confirmed`; reject it when a fact refutes it, or when nothing but the hint itself speaks for it; mark it unsettled when the facts are inconclusive. A hint whose row says undetermined, a hint no row names at all, and a hint that is merely plausible are never accepted, however sound they read. Two hints of one group are two decisions: the verdict of one says nothing about the other. Severity is measured against the quality criteria named in the task, not against your taste.\n\nWrite `{out}`: the accepted list, each row with the hint id, the place, the required change in one sentence and the fact it rests on; the rejected list with the refuting fact; the unsettled list exactly as the task gives it \u2014 those rows are what the run returns to the user, so you copy them and add none of your own. Two hints about one place that need one change are one row, keeping both aspect tags and both ids.\n\nNever change the object, never add a finding nobody hinted at, never accept a hint because it sounds reasonable.\n\nReturn: the output path and the three counts, then the accepted rows themselves \u2014 one line per accepted hint id, nothing else on the line:\n\n`ACCEPTED | g1.h2 | cut the trailing dash after the slice, at slug.js:4`\n\nOnly those lines open the change stage: a row that stands in `{out}` but on no line of your return is a row nobody got, and a count is no row. Accept nothing you did not accept there. When you accepted nothing, write no such line. Then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "fixer": "Fixer. You change the object by the accepted list the task names, and by nothing else. That list is the whole mandate: an improvement nobody accepted is scope you may not add, and a row that stands in a file you read but not in the task's list is not yours to apply.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nPer accepted row: make the smallest change that satisfies it, at the place it names. A row you disagree with is not dropped and not reinterpreted \u2014 make the change and say in your return why you think it is wrong, or, when the change would break something the row did not see, stop at that row and report it with the evidence.\n\nAfter the changes run the check the task names and quote its decisive line. When the check fails after your change, fix your change; when it already failed before it, say so with both runs.\n\nNever touch a place no row names, never commit, never push.\n\nList every changed path in `{out}`, one per line, and write nothing else into it.\n\nReturn: the changed paths, the rows you could not apply, the decisive line of the check verbatim, then the last line `DONE` or `BLOCKED: <reason>`.\n",
}
// ---- end roles ----

// ---- aspects (generated by bin/build.sh from lib/aspects/*.md; never edit here) ----
const ASPECT_TEXT = {
  "cost": "Aspect: cost. Read the object for work paid for and not used: a whole file read to answer one question, the same context carried through stages that do not need it, a heavy step run where a cheap check would decide, a repeat of work whose result already sits on disk, a wide search where the task named the place.\n\nTypical shapes: a stage that reads everything and uses one line; a loop that repeats an expensive step because nobody kept its result; a review over output an executable check already settles; work started before the cheap condition that would have skipped it; a long text pasted where a path would do.\n\nOut of scope: prices, budgets and billing, the choice of who does the work, and the cost the object's stated constraints accept. A hint names the wasted work, the place it happens, and the cheaper order that gets the same result.\n",
  "data-integrity": "Aspect: data integrity. Read the object for the places where data can be lost, silently changed or contradicted: a write that is not atomic, a file two writers share, a record updated without the check that it is the one meant, a conversion that drops a field, a default that overwrites a value somebody set.\n\nTypical shapes: read-modify-write with no guard against a second writer; a partial result left on disk when a step dies; an identifier reused after a rename; a migration with no way back; two stores holding the same fact with no check that they agree; truncation, encoding or rounding that nobody notices.\n\nOut of scope: schema taste, storage choice, and durability guarantees the object's stated constraints hand to another component. A hint names the record, the moment it can be damaged, and how one would see it afterwards.\n",
  "extensibility": "Aspect: extensibility. Read the object for the change that will come next and what it will cost: a fact repeated in several files so the next edit must find all of them, a list one place enumerates and another place assumes, a hard-coded case where the shape asks for a table, a contract stated in prose on one side and in code on the other.\n\nTypical shapes: adding one case means touching five files; a new name must be added to a regex, a doc and a map that nobody links; a default buried in a branch instead of stated once; two sources for one truth, with no check that they agree.\n\nOut of scope: extension points for a case nobody named, plug-in machinery for one implementation, and future work the object's own scope excludes. A hint names the concrete next change and the places it would have to touch.\n",
  "operability": "Aspect: operability. Read the object as the person who has to run it, watch it and repair it at the worst moment: can they tell what happened, where it stopped, what to do next, and can they undo it?\n\nTypical shapes: a failure with no message naming the input that caused it; a run that leaves no record of what it did; a state file nobody can read by hand; a step that is not safe to run twice; no way to resume after a death in the middle; a message that names an internal symbol instead of the action that failed; an irreversible step with no confirmation and no backup.\n\nOut of scope: monitoring stacks, dashboards and alerting policy, and operations the object's stated scope hands to somebody else. A hint names the moment of trouble and what the operator would be missing then.\n",
  "performance": "Aspect: performance. Read the object for work done more often than the result is used: a read inside a loop that could stand outside it, a whole file loaded to answer one question, a repeated call with the same argument, a scan where an index or a map exists, a wait that holds a costly context open while nothing happens.\n\nTypical shapes: quadratic work over a list that grows with the input; a command run once per item instead of once per batch; data copied between stages that could be passed by path; an early exit nobody takes; a cache that never hits because its key carries a timestamp.\n\nOut of scope: micro-optimisation of code that runs once, guesses with no measurement, and limits the object's stated constraints accept. A hint names the input size at which the cost bites and the measurement that would show it.\n",
  "reliability": "Aspect: reliability. Read the object for the states nobody planned for: an error swallowed, a return nobody checks, a failure that looks like success, a retry that repeats a side effect, a partial write left behind, a timeout with no upper bound, an order two steps can take in either sequence.\n\nTypical shapes: a check that passes on missing input because the missing value compares equal to the good one; a cleanup that runs only on the happy path; a counter that resets on restart; a condition read once and used after it can have changed; a failure reported in a place nobody reads.\n\nOut of scope: performance, scalability, security, and a failure mode the object's stated constraints put outside its job. Name the state that breaks it and how one would reach that state; a worry with no reachable path is not a hint.\n",
  "scalability": "Aspect: scalability. Read the object for what breaks when the number grows: more items, more parallel runs, more callers, a bigger file, a longer list than the author pictured. Look for a limit that is stated nowhere and enforced nowhere.\n\nTypical shapes: everything held in memory at once; an unbounded fan-out of parallel work; a shared file two runs write at the same time; an identifier that collides on the second concurrent run; a queue with no ceiling; a cost that rises with the total instead of with the change.\n\nOut of scope: capacity planning, infrastructure sizing, and growth the object's stated constraints exclude (\"one repository, one user\"). A hint names the quantity that grows, the place that assumes it small, and what happens at the first size that does not fit.\n",
  "security": "Aspect: security. Read the object for what an untrusted input, an untrusted file or an untrusted caller can reach: a value interpolated into a shell line, a path joined without a boundary check, a secret written into a log, an argument that decides which file is read or deleted, a permission widened for convenience, a token passed further than it must travel.\n\nTypical shapes: data from outside reaching an interpreter (shell, SQL, template, eval); a check done once and the value used twice; a comparison of secrets that leaks by short-circuit; credentials in an argument list; an irreversible action behind an unchecked flag.\n\nOut of scope: threats the object's stated boundary excludes, hardening nobody asked for, and rating the general strength of a mechanism the object only uses. Name the input, the path it travels and what it reaches; a hint with no path is not a hint.\n",
  "simplicity": "Aspect: simplicity. Read the object for what costs more than it buys: an abstraction with one caller, a parameter nobody passes, a branch no input reaches, two helpers doing one job, a layer that only forwards, a general mechanism built for a case that never came, state kept where a value would do.\n\nTypical shapes: a flag that switches behavior at one call site; a name that hides what the code does; a rule stated in three places and true in one; a configuration key with a single value; code kept because deleting it looked risky.\n\nOut of scope: naming style, formatting, line length, taste, the choice of language idiom, anything the object's own stated constraints demand, and a shape a caller, a test or the object's own rules need. A shape you would have written differently is not a hint; a shape that carries cost nobody pays for is.\n",
  "testability": "Aspect: testability. Read the object for the claims nobody can check: a decision buried where no test can reach it, a pure rule mixed into a side effect, a behavior provable only by running a whole session, a check that passes whatever the code does.\n\nTypical shapes: logic inside a file no harness loads; a test that asserts the code as written instead of the wanted behavior; a check with no failing case, so a mutation of the code leaves it green; output nobody can compare because it carries a timestamp; an assertion on a message string that says nothing about the result.\n\nOut of scope: coverage numbers, the choice of harness, tests for code the object's scope excludes, and demanding a test where the verification plan already recorded that no oracle is possible. A hint names the claim and the shape that keeps it out of reach.\n",
}
// ---- end aspects ----

// Verification-first (lib/verification.md): this flow runs where no oracle can decide, ladder
// level e. Where an executable check exists it is the oracle and this chain is not the route; the
// `test` argument only lets the evidence stage and the fixer use that check as a fact.
//
// The four stages of idea 3.6. Every decision between them — the hint cap, the grouping by place,
// the form of the chain, the two kinds of failure, the control run on the base version and what
// may reach the one who changes the object — lives in the shared block as a pure function, so a
// test executes it instead of reading this file.

// The tool-set agents this flow may launch, as literals: a role whose agent is not one of them is
// a defect of the role map, not a launch this script may make.
const AGENTS = ['session:tools-edit', 'session:tools-read-bash', 'session:tools-read-write']
// An agent with Bash counts its own output; one with Read only reads the file back.
const BASH_AGENTS = ['session:tools-edit', 'session:tools-read-bash']
// The stage roles, from the stamped subset of this script.
const CRITIC = 'critic'
const RESEARCH = 'evidence-researcher'
const MERGED = 'evidence'
const TRIAGE = 'evidence-triage'
const FIXER = 'fixer'

let A = args || {}
if (typeof A === 'string') A = JSON.parse(A)
const IN = A.in == null ? [] : A.in
const ASK = A.ask
const OUT = A.out
const ASPECTS = A.aspects == null ? [] : A.aspects
const DEPTH = A.depth || 'std'
const BASE = A.base || 'HEAD'
const TEST = A.test || null
const CLS = A.class || CLASSES.defaultClass
const SIZE = A.size || CLASSES.defaultSize
const SUBS = A.submodes == null ? [] : A.submodes

// Every argument error returns instead of throwing: the launcher gets the catalog back and can fix
// the call without reading this script.
const fail = (why, extra) => ({ blocked: blockedLine(why), ...(extra || {}) })

// The launch line is logged before the first argument check: a call that returns an argument error
// without logging leaves no line in /workflows and reads as a call that never happened.
log(`${[CLS, ...(Array.isArray(SUBS) ? SUBS : [])].join('-')}-chain | depth=${DEPTH} aspects=${Array.isArray(ASPECTS) ? ASPECTS.join(',') : '(no array)'} in=${Array.isArray(IN) ? IN.length : '(no array)'} out=${OUT || '(none)'} base=${BASE}`)

if (!Array.isArray(IN) || !IN.length) return fail('args.in must be a JSON array of absolute paths, the object under review')
if (!ASK) return fail('args.ask (what changed and what to judge, in prose) is required')
if (!OUT) return fail('args.out (one absolute path for the result file) is required')
// a relative out would still match an agent's return, so the output check would pass over a file
// nobody can find: the contract says absolute, and the script holds the launcher to it
if (typeof OUT !== 'string' || OUT[0] !== '/' || OUT.lastIndexOf('/') < 1) return fail(`args.out must be an absolute path, got ${OUT}`)
if (!CLASSES.table[CLS]) return fail(`unknown class ${CLS}`, { classes: Object.keys(CLASSES.table) })
if (!CLASSES.sizes.includes(SIZE)) return fail(`unknown size ${SIZE}`, { sizes: CLASSES.sizes })
if (!CLASSES.ceilings[DEPTH]) return fail(`unknown depth ${DEPTH}`, { depths: Object.keys(CLASSES.ceilings) })
if (!Array.isArray(SUBS)) return fail('args.submodes must be a JSON array', { submodes: CLASSES.submodeOrder })
const BADSUB = SUBS.filter(s => !CLASSES.submodeOrder.includes(s))
if (BADSUB.length) return fail(`unknown submode ${BADSUB.join(' ')}`, { submodes: CLASSES.submodeOrder })
if (SUBS.length === 3) return fail('all three submodes banned: nothing left to run on')
if (!Array.isArray(ASPECTS)) return fail('args.aspects must be a JSON array of catalog names', { aspects: Object.keys(ASPECT_TEXT) })
// The plan of the critic stage is one decision of the shared block, executed by the test instead
// of read out of this file: the gate of the `aspects` argument (an unknown name selects no
// paragraph, so the run stops before any agent, 3.6), the split into one merged critic at lite and
// one critic per aspect above it (A3), and the ceiling of A30 over them — the critics that do not
// fit never start, their aspects become the gap, never a second round.
const PLAN = chainPlan(DEPTH, ASPECTS, ASPECT_TEXT)
if (!PLAN.ok) return fail(PLAN.why, { aspects: PLAN.known })

const RUN = bindClass(CLS, SUBS)
const DIR = OUT.slice(0, OUT.lastIndexOf('/'))
const side = stem => `${DIR}/chain-${stem}.md`
const INLIST = IN.join('\n')
const ROOM = PLAN.room

// a split critic sits one slot down, which is what roleSlot's split flag carries (A3)
const CRITIC_SLOT = roleSlot(CRITIC, SIZE, PLAN.split)
const PLANRUN = PLAN.sets
const CGAP = PLAN.gap

const fillRole = (role, fields) => {
  const missed = []
  const text = ROLE_TEXT[role].replace(/\{([A-Za-z][A-Za-z0-9_-]*)\}/g, (m, k) => {
    if (!Object.prototype.hasOwnProperty.call(fields, k)) { missed.push(k); return m }
    return fields[k]
  })
  return { text, missed }
}
// the size line is the only evidence a script without file access has that a file was written
const tail = (out, agentType, shape) => `\n\nWork only inside the directories the paths above name. Write ${out} yourself. Start your return with one line \`${out} <n> bytes\` giving the size of what you wrote (${BASH_AGENTS.includes(agentType) ? 'count it with `wc -c`' : `read ${out} back with your Read tool and count what it holds, never a number from memory`}), then ${shape} A file you did not write, or left empty, is not a finished job: return BLOCKED: <why> instead of a size. On a permission denial stop at once and return BLOCKED: <the denied action>.`

async function stage(role, slot, job, phaseName, fields, shape) {
  const agentType = `session:${roleAgent(role)}`
  // a stage that never started still names its output path: a caller that collected the paths of
  // the blocked runs too would hand the next stage a file nobody wrote
  if (!AGENTS.includes(agentType)) return { out: fields.out, ok: false, ret: '', blocked: blockedLine(`role ${role} names no tool-set agent of this flow: ${agentType}`) }
  const f = fillRole(role, fields)
  if (f.missed.length) return { out: fields.out, ok: false, ret: '', blocked: blockedLine(`role text of ${role} reads ${f.missed.join(' ')}, outside the argument shape`) }
  const o = RUN.opts(slot, job, { agentType, phase: phaseName })
  const r = await agent(f.text + tail(fields.out, agentType, shape), o)
  const v = outVerdict(r, fields.out)
  return { out: fields.out, label: o.label, ret: String(r == null ? '' : r), ok: v.ok, blocked: v.ok ? null : v.blocked }
}

// ---- 1. the critics: hints, never verdicts, at most HINT_CAP each (A27) ----
phase('Critique')
const HINT_SHAPE = `one line per hint, in this exact shape and nothing else on the line:
HINT | <aspect> | <place: path:from-to, or file.md#Section> | high|medium|low | <the error you suspect, one sentence> | <the evidence that would settle it>
Only those lines are read by the flow; a hint that is not on such a line reaches nobody. At most ${HINT_CAP} hints, the strongest first, then the last line \`DONE\` or \`BLOCKED: <reason>\`.`

const critiques = await parallel(PLANRUN.map((set, i) => async () => {
  const label = set.join('-') || 'merged'
  const out = side(`hints-${label}`)
  const ASPECT_BLOCK = `\n\nRead the object through ${set.length === 1 ? 'this aspect only' : 'these aspects only'}, and give hints on nothing else:\n\n${set.map(n => ASPECT_TEXT[n]).join('\n')}`
  const s = await stage(CRITIC, CRITIC_SLOT, `critic-${label}`, 'Critique',
    { in: INLIST, ask: `${ASK}${ASPECT_BLOCK}`, out }, HINT_SHAPE)
  return { ...s, set, label }
}))

const LIVE = critiques.filter(c => c.ok)
if (!LIVE.length) {
  return { out: null, stage: 'critique', blocked: blockedLine(`every critic returned blocked: ${critiques.map(c => `${c.label}: ${c.blocked}`).join(' ;; ')}`) }
}
// the cap is applied per critic, so N critics give at most HINT_CAP x N hints before grouping
// a hint line that left the aspect field empty still carries the aspect tag of the critic that
// wrote it — for the merged critic the whole set it read, so no group ends up with no tag at all
const HINTS = LIVE.map(c => capHints(parseHints(c.ret, c.set.join('+')))).reduce((a, b) => a.concat(b), [])
// two critics pointing at the same place form one group, with both aspect tags and the higher
// severity: one group is one evidence run, never two (3.6, merge and dedupe in the script)
const GROUPS = groupHints(HINTS)
const TOP = maxSeverity(GROUPS)
const FORM = chainForm(DEPTH, TOP)
log(`${RUN.name('chain')} | critics=${PLANRUN.length}/${PLANRUN.length + CGAP.length} slot=${CRITIC_SLOT} hints=${HINTS.length} groups=${GROUPS.length} severity=${TOP || 'none'} form=${FORM}`)

// the gap of the critic stage: an aspect nobody read, because the ceiling of this depth was full
const CGAPTEXT = CGAP.map(set => `${set.join(', ')}: no critic, the ceiling of ${ROOM} agents per stage was full`)

if (!GROUPS.length) {
  return {
    out: null, form: FORM, critics: PLANRUN.length, aspects: ASPECTS, groups: 0, confirmed: 0, fixing: 0,
    undetermined: [], unanswered: [], harness: [], onBase: [], gap: CGAPTEXT,
    note: `${PLANRUN.length} critic(s) over ${ASPECTS.join(', ')} found no place worth a fact; nothing was changed.`,
    status: chainStatus({ form: FORM, groups: 0, confirmed: 0, undetermined: 0, unanswered: 0, out: OUT, gap: CGAP.length, room: ROOM }),
    blockedStages: critiques.filter(c => !c.ok).map(c => `critic ${c.label}: ${c.blocked}`),
  }
}

// the depth ceiling counts the agents of one stage (A30): what does not fit ends the stage and is
// written into the result as a gap, never retried in a second round. The seating itself is a
// decision of the shared block, so a test executes it.
const RUNS = chainEvidenceRuns(DEPTH, FORM, GROUPS)
const RUNGROUPS = RUNS.ran
const GAP = RUNS.gap

// every hint carries its own id: the answers are per hint, so a group holding a confirmed hint and
// a refuted one cannot carry the refuted one to the fixer under one group verdict (A28)
const groupText = gs => gs.map(g => `${g.id} | ${g.place} | ${g.severity} | aspects: ${g.aspects.join(', ')}\n${g.hints.map(h => `    ${h.id} | ${h.place} | ${h.what} (evidence: ${h.evidence})`).join('\n')}`).join('\n')
const EVIDENCE_SHAPE = `one line per hint, in this exact shape and nothing else on the line:
EVIDENCE | <hint id, like g1.h2> | confirmed|refuted|undetermined|harness | base:yes|base:no | <the pointer: file and line, the command with its decisive output line, or a commit>
Answer every hint of your group on its own line, with that hint's own id: one verdict written over a whole group settles no hint of it and reaches nobody.
\`confirmed\` needs a fact of the object — file and line, or the command with its decisive output line — that holds this one hint up. A hint the files and the runs neither hold up nor settle is \`undetermined\`, never \`confirmed\`: plausible is not confirmed, and a hint nobody settled goes to the user, not to the one who changes the object.
\`refuted\` is the answer as soon as a fact stands against the hint: a caller, a test or a rule of the object's own documents that needs what the hint calls needless, or a value that shows the claimed failure does not happen.
\`harness\` is a failure of your own run (tool, access, sandbox), never a finding about the object. \`base:yes\` means the same failure, or the same shape, already stands in the unchanged base version ${BASE}, which makes it no finding of this change. Then the last line \`DONE\` or \`BLOCKED: <reason>\`.`
const CONTROL = `Control run: before you call anything a finding of this change, hold the hint against the unchanged base version ${BASE}. A hint that claims a failure: run the same check there too and say which of the two runs failed. A hint that claims a shape — a duplicate, a wrapper, a name, a needless mechanism: read the same place there and say whether that shape already stands in it. A failure or a shape the base version already carries is \`base:yes\` and no finding of this change.${TEST ? ` The check of this task is: \`${TEST}\`.` : ' No check command was given: use the smallest command that settles the hint.'}`

const GAPTEXT = [...CGAPTEXT, ...GAP.map(g => `${g.id} at ${g.place}: the ceiling of ${ROOM} agents per stage ended the evidence stage`)]
// Every return from the evidence stage on is built by chainResult() of the shared block: a stage
// that blocks late carries the same rows as a run that reached the end — the open ones above all
// (A28). The state it reads is filled in as the run goes: `answers` and `decided` by the evidence
// stage, LATE by a stage that blocked after it, so a blocked return is never a bare line.
let answers = []
let decided = { files: [], blocked: [] }
const LATE = []
const result = extra => chainResult({
  out: OUT, form: FORM, aspects: ASPECTS, critics: PLANRUN.length, base: BASE,
  groups: GROUPS, ran: RUNGROUPS, answers, evidence: decided.files, gap: GAPTEXT,
  gapCount: CGAP.length + GAP.length, room: ROOM,
  blockedStages: [
    ...critiques.filter(c => !c.ok).map(c => `critic ${c.label}: ${c.blocked}`),
    ...(decided.blocked || []), ...LATE,
  ],
  ...(extra || {}),
})

// ---- 2. the evidence: long form one researcher per group, short form one agent that decides ----
phase('Evidence')
if (FORM === 'long') {
  const runs = await parallel(RUNGROUPS.map(g => async () => {
    const out = side(`evidence-${g.id}`)
    const s = await stage(RESEARCH, roleSlot(RESEARCH, SIZE), `evidence-${g.id}`, 'Evidence', {
      in: [...IN, ...LIVE.map(c => c.out)].join('\n'),
      ask: `${ASK}\n\nHint group ${g.id}, at ${g.place}:\n${groupText([g])}\n\n${CONTROL}`,
      out,
    }, EVIDENCE_SHAPE)
    return s
  }))
  answers = runs.filter(r => r.ok).map(r => parseEvidence(r.ret)).reduce((a, b) => a.concat(b), [])
  // only the files a run really wrote go on; a blocked run names a path nobody created
  decided = { files: runs.filter(r => r.ok).map(r => r.out), blocked: runs.filter(r => !r.ok).map(r => r.blocked) }
} else {
  // short form: stages 2 and 3 merge into one agent that collects the facts and decides them
  const s = await stage(MERGED, roleSlot(MERGED, SIZE), 'evidence', 'Evidence', {
    in: [...IN, ...LIVE.map(c => c.out)].join('\n'),
    ask: `${ASK}\n\nHint groups:\n${groupText(RUNGROUPS)}\n\n${CONTROL}`,
    out: OUT,
  }, `${EVIDENCE_SHAPE}
Write the same decision into ${OUT}: accepted with the change in one sentence, rejected with the refuting fact, undetermined with what is missing, and the failures of your own run in their own list.`)
  // a blocked short form returns through the result builder too: the critic gap, the blocked
  // critic stages and the status sentence stand in it, the same way a blocked triage does (A28)
  if (!s.ok) {
    decided = { files: [], blocked: [`evidence: ${s.blocked}`] }
    return result({ stage: 'evidence', blocked: s.blocked, fixed: 'the evidence stage was blocked: nothing was changed' })
  }
  answers = parseEvidence(s.ret)
  decided = { files: [OUT], blocked: [] }
}

// the two rules that keep a finding honest: a failure of our own harness is no finding about the
// object, and a failure that also reproduces on the base version is no finding of this change
const SPLIT = splitFailures(answers)
// the one table of the run: the rows the return carries and the rows the result file must hold
// are these, rendered once by the shared block, so the file and the return cannot disagree (A28)
const ROWS = chainRows(RUNGROUPS, answers)
const UND = ROWS.undetermined
// a hint that ran and came back with no readable answer is settled by nothing: it goes to the
// user with the undetermined ones instead of disappearing from every list (A28)
const NOANSWER = ROWS.unanswered
log(`${RUN.name('chain')} | answers=${answers.length} findings=${SPLIT.findings.length} harness=${SPLIT.harness.length} on-base=${SPLIT.onBase.length} undetermined=${UND.length} unanswered=${NOANSWER.length}`)

// ---- 3. the judge (long form only): the accepted list, with the fact each row rests on ----
let judged = null
const ACCEPT_SHAPE = `one line per accepted row, in this exact shape and nothing else on the line:
ACCEPTED | <hint id, like g1.h2> | <the change in one sentence>
Only those lines open the fix stage, and they are the fixer's whole mandate: a hint you rejected or left unsettled, and any hint the fact list below does not mark \`confirmed\`, must not appear among them. One accepted row names one hint id. Then the last line \`DONE\` or \`BLOCKED: <reason>\`.`
if (FORM === 'long') {
  phase('Triage')
  const factText = ROWS.findings.map(r => `${r.id} | ${r.place} | ${r.answered ? r.verdict : 'no answer came back'} | ${r.pointer}`).join('\n') || '(no fact came back)'
  // the open rows of this run, rendered by the shared block from the same table the return carries:
  // the judge copies them instead of composing a list of its own, or the file and the return would
  // tell two different stories (A28)
  const openText = ROWS.open.length ? `\n\nUnsettled rows, exactly these and no others. Copy them into ${OUT} under a heading \`Unsettled\`, one row each, as \`| hint id | place | what is missing |\`, and accept none of them:\n${openRowsText(ROWS)}` : `\n\nNothing is unsettled in this run: write an \`Unsettled\` section into ${OUT} saying so, and add no row of your own to it.`
  judged = await stage(TRIAGE, roleSlot(TRIAGE, SIZE), 'triage', 'Triage', {
    in: [...LIVE.map(c => c.out), ...decided.files].join('\n'),
    ask: `${ASK}\n\nHint groups:\n${groupText(RUNGROUPS)}\n\nFacts about the object, one row per hint (the failures of our own runs and the failures that reproduce on the base version ${BASE} are already out and are no findings). Accept a hint only when its own row says \`confirmed\`: a hint that sounds reasonable, that its row leaves undetermined, or that no row names at all, is never accepted:\n${factText}${openText}${GAP.length ? `\n\nNo fact was collected for these groups, the depth ceiling of ${ROOM} agents ended the stage: ${GAP.map(g => `${g.id} at ${g.place}`).join(', ')}. They are unsettled, not rejected.` : ''}`,
    out: OUT,
  }, ACCEPT_SHAPE)
  if (!judged.ok) {
    LATE.push(`triage: ${judged.blocked}`)
    return result({ stage: 'triage', blocked: judged.blocked, fixed: 'the triage stage was blocked: nothing was changed' })
  }
}

// ---- 4. the fix: only what the judge accepted, and only what a fact confirmed (A28) ----
// A hint without evidence changes nothing, so the fixer starts only on a hint a fact confirmed;
// undetermined, refuted, harness and base-version answers never open this stage. In the long form
// the accepted rows of the judge are the mandate, never the raw evidence verdicts: a hint the
// judge rejected stays out, and a judge who accepted nothing opens no fix stage.
const TOFIX = FORM === 'long'
  ? judgedInput(RUNGROUPS, answers, parseAccepted(judged.ret))
  : fixerInput(RUNGROUPS, answers)
// the mandate is named hint by hint: the fixer never reads a wider row out of the result file
const FIXTEXT = TOFIX.map(g => (g.hints || []).length
  ? g.hints.map(h => `${h.id} at ${h.place || g.place}: ${h.what}`).join('\n')
  : `${g.id} at ${g.place}`).join('\n')
let fixed = null
if (TOFIX.length) {
  phase('Fix')
  fixed = await stage(FIXER, roleSlot(FIXER, SIZE), 'fix', 'Fix', {
    in: [OUT, ...IN].join('\n'),
    ask: `${ASK}\n\nApply these accepted rows, and nothing else. They are the whole mandate: a row of ${OUT} that is not in this list, however it reads there, is not yours to change.\n${FIXTEXT}\n${TEST ? `After the change run \`${TEST}\` and quote its decisive line.` : 'No check command was given: say so instead of inventing one.'}`,
    out: side('changed'),
  }, `the changed paths and the last line \`DONE\` or \`BLOCKED: <reason>\`.`)
}

// A blocked fixer is a failed run, not a finished one: it names the stage, carries the blocked
// line and stands in the blocked stages, so no caller reads it as a run that applied its rows.
if (fixed && !fixed.ok) {
  LATE.push(`fix: ${fixed.blocked}`)
  return result({
    stage: 'fix', blocked: fixed.blocked, fixing: TOFIX.length,
    fixed: `the fix stage was blocked, nothing was changed: ${fixed.blocked}`,
  })
}

// One round: critique, evidence, judgement, fix. A second critique needs the user's word, so the
// flow ends here and the status says what is left open. `fixing` is the count the fix stage got;
// the `confirmed` count of the result is the facts, which chainResult reads off the answers.
return result({
  fixing: TOFIX.length,
  fixed: fixed ? fixed.out : 'no accepted row: nothing was changed',
})
