export const meta = {
  name: 'role',
  description: 'One role, one agent',
  whenToUse: 'One job for one agent: author, critic, researcher, executor, translator, waiter and the rest of the catalog. The role text lives in the script; the launch passes arguments only.',
  phases: [{ title: 'Role' }],
}
/* usage:
One catalog role, one agent, one output file.
role (string, required): plan-author spec-author scenario-author code-author test-author coverage-checker critic evidence-researcher evidence evidence-triage fixer researcher web-researcher synthesizer executor waiter translator
in (array of absolute paths, default [])
ask (string, the job or question in prose, required)
out (string, absolute output path, required)
class (string c1-c5, default c3)
submodes (array of strings: no-sonnet no-opus no-fable, default [])
size (string small medium large, default medium; large moves the role one slot down)
Out: the file named by out; returns {role, out, class, slot, label}; failure returns blocked: "BLOCKED: <why>".
Use: a job of one agent. Not: a flow of several roles.
*/

// ---- shared block (generated by bin/build.sh from lib/block.src.js; never edit here) ----
// Shared script block. Source of truth: lib/block.src.js plus lib/classes.json; edit those only.
// bin/build.sh renders them into lib/block.js and stamps lib/block.js between the shared-block
// markers of every target named by lib/build-manifest.json. lib/block.js and every stamped copy
// are generated: a hand edit inside them is lost at the next build and fails `bin/build.sh --check`.
// Scripts cannot import, so every workflow carries a byte-identical copy of this block.
// Pure functions only: no file access, no harness global (`args`, `agent`, `log`), no side effect.

// ---- class table ----
const CLASSES = {
  "defaultClass": "c3",
  "slots": [
    "main",
    "opus",
    "sonnet"
  ],
  "slotDown": {
    "main": "opus",
    "opus": "sonnet",
    "sonnet": "sonnet"
  },
  "sizes": [
    "small",
    "medium",
    "large"
  ],
  "defaultSize": "medium",
  "models": {
    "fab": "fable",
    "ops": "opus",
    "son": "sonnet"
  },
  "efforts": {
    "lo": "low",
    "me": "medium",
    "hi": "high"
  },
  "submodeOrder": [
    "no-sonnet",
    "no-opus",
    "no-fable"
  ],
  "submodeKeys": [
    "none",
    "no-sonnet",
    "no-opus",
    "no-fable",
    "no-sonnet no-opus",
    "no-sonnet no-fable",
    "no-opus no-fable"
  ],
  "table": {
    "c1": {
      "none": "ops-lo/ops-lo/son-lo",
      "no-sonnet": "ops-lo/ops-lo/ops-lo",
      "no-opus": "son-me/son-me/son-lo",
      "no-fable": "ops-lo/ops-lo/son-lo",
      "no-sonnet no-opus": "fab-lo/fab-lo/fab-lo",
      "no-sonnet no-fable": "ops-lo/ops-lo/ops-lo",
      "no-opus no-fable": "son-me/son-me/son-lo"
    },
    "c2": {
      "none": "fab-lo/ops-lo/son-me",
      "no-sonnet": "fab-lo/ops-lo/ops-lo",
      "no-opus": "fab-lo/son-me/son-me",
      "no-fable": "ops-me/ops-lo/son-me",
      "no-sonnet no-opus": "fab-lo/fab-lo/fab-lo",
      "no-sonnet no-fable": "ops-me/ops-lo/ops-lo",
      "no-opus no-fable": "son-me/son-me/son-me"
    },
    "c3": {
      "none": "fab-lo/ops-me/son-hi",
      "no-sonnet": "fab-lo/ops-me/ops-me",
      "no-opus": "fab-lo/son-hi/son-hi",
      "no-fable": "ops-me/ops-me/son-hi",
      "no-sonnet no-opus": "fab-lo/fab-lo/fab-lo",
      "no-sonnet no-fable": "ops-me/ops-me/ops-me",
      "no-opus no-fable": "son-me/son-hi/son-hi"
    },
    "c4": {
      "none": "fab-me/ops-hi/son-hi",
      "no-sonnet": "fab-me/ops-hi/ops-me",
      "no-opus": "fab-me/fab-me/son-hi",
      "no-fable": "ops-hi/ops-hi/son-hi",
      "no-sonnet no-opus": "fab-me/fab-me/fab-lo",
      "no-sonnet no-fable": "ops-hi/ops-hi/ops-me",
      "no-opus no-fable": "son-hi/son-hi/son-hi"
    },
    "c5": {
      "none": "fab-hi/ops-hi/ops-hi",
      "no-sonnet": "fab-hi/ops-hi/ops-hi",
      "no-opus": "fab-hi/fab-me/fab-me",
      "no-fable": "ops-hi/ops-hi/ops-hi",
      "no-sonnet no-opus": "fab-hi/fab-me/fab-me",
      "no-sonnet no-fable": "ops-hi/ops-hi/ops-hi",
      "no-opus no-fable": "son-hi/son-hi/son-hi"
    }
  },
  "classStep": {
    "c1": "c2",
    "c2": "c3",
    "c3": "c4",
    "c4": "c5",
    "c5": "c5"
  },
  "roles": {
    "plan-author": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": true
    },
    "spec-author": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": true
    },
    "scenario-author": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": true
    },
    "code-author": {
      "agent": "tools-edit",
      "slot": "sonnet",
      "uplift": false
    },
    "test-author": {
      "agent": "tools-edit",
      "slot": "sonnet",
      "uplift": false
    },
    "coverage-checker": {
      "agent": "tools-read-write",
      "slot": "sonnet",
      "uplift": false
    },
    "critic": {
      "agent": "tools-read-write",
      "slot": "main",
      "splitSlot": "opus",
      "uplift": false
    },
    "evidence-researcher": {
      "agent": "tools-read-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "evidence": {
      "agent": "tools-read-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "evidence-triage": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": false
    },
    "fixer": {
      "agent": "tools-edit",
      "slot": "opus",
      "uplift": false
    },
    "researcher": {
      "agent": "tools-read-write-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "web-researcher": {
      "agent": "tools-web",
      "slot": "sonnet",
      "uplift": false
    },
    "synthesizer": {
      "agent": "tools-read-write",
      "slot": "main",
      "uplift": true
    },
    "executor": {
      "agent": "tools-read-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "waiter": {
      "agent": "tools-read-bash",
      "slot": "sonnet",
      "uplift": false
    },
    "translator": {
      "agent": "tools-read-write",
      "slot": "opus",
      "uplift": false
    }
  },
  "ceilings": {
    "lite": {
      "agents": 2,
      "cycles": 1
    },
    "std": {
      "agents": 5,
      "cycles": 2
    },
    "full": {
      "agents": 10,
      "cycles": 3
    }
  }
}
// ---- end class table ----

const MODEL_NAME = CLASSES.models
const EFFORT_NAME = CLASSES.efforts

// submodes(list) -> { subs, key }: submodes in the table's order, the row key of the class table.
function submodes(list) {
  const given = list || []
  const bad = given.filter(s => !CLASSES.submodeOrder.includes(s))
  if (bad.length) throw new Error(`unknown submode ${bad.join(' ')}`)
  const subs = CLASSES.submodeOrder.filter(s => given.includes(s))
  if (subs.length === 3) throw new Error('all three submodes banned: nothing left to run on')
  return { subs, key: subs.join(' ') || 'none' }
}

// cellFor(class, submodes) -> { main, opus, sonnet }, each the short cell of the class table.
function cellFor(cls, subs) {
  const row = CLASSES.table[cls]
  if (!row) throw new Error(`unknown class ${cls}`)
  const parts = row[submodes(subs).key].split('/')
  return { main: parts[0], opus: parts[1], sonnet: parts[2] }
}

// optsFor(class, submodes, slot, job) -> { model, effort, label } for one agent() call.
function optsFor(cls, subs, slot, job, extra) {
  const cell = cellFor(cls, subs)
  if (!Object.prototype.hasOwnProperty.call(cell, slot)) throw new Error(`unknown slot ${slot}`)
  const short = cell[slot]
  const m = short.split('-')[0]
  const e = short.split('-')[1]
  // `extra` spreads first: a call site adds keys (agentType, tools) but never overrides the model,
  // the effort or the label, which only the class table decides.
  return { ...(extra || {}), model: MODEL_NAME[m], effort: EFFORT_NAME[e], label: `${short}-${job}` }
}

// classUp(class): the one class step of 3.5 rule 2 and rule 3; the top class steps to itself.
function classUp(cls) {
  const next = CLASSES.classStep[cls]
  if (!next) throw new Error(`unknown class ${cls}`)
  return next
}

// slotForSize(slot, size): a large input moves a role one slot down, never up, never past the
// cheapest slot (A32; the launcher states the volume, a script cannot measure its inputs).
function slotForSize(slot, size) {
  if (!CLASSES.slots.includes(slot)) throw new Error(`unknown slot ${slot}`)
  const s = size || CLASSES.defaultSize
  if (!CLASSES.sizes.includes(s)) throw new Error(`unknown size ${s}`)
  return s === 'large' ? CLASSES.slotDown[slot] : slot
}

// bindClass(class, submodes): the class of one run; every stage asks it for its agent options.
function bindClass(cls, subs) {
  const s = submodes(subs)
  const cell = cellFor(cls, s.subs)
  return {
    class: cls,
    submodes: s.subs,
    cell,
    name: stem => [cls, ...s.subs, stem].join('-'),
    opts: (slot, job, extra) => optsFor(cls, s.subs, slot, job, extra),
    up: () => bindClass(classUp(cls), s.subs),
  }
}

// roleOf / roleAgent / roleSlot / roleClass: the per-role slot map of lib/classes.json.
function roleOf(name) {
  const r = CLASSES.roles[name]
  if (!r) throw new Error(`unknown role ${name}`)
  return r
}
function roleNames() { return Object.keys(CLASSES.roles) }
function roleAgent(name) { return roleOf(name).agent }
function roleSlot(name, size, split) {
  const r = roleOf(name)
  return slotForSize(split && r.splitSlot ? r.splitSlot : r.slot, size)
}
// roleClass(role, class): an output no oracle can check gets a stronger author, one class step up.
function roleClass(name, cls) { return roleOf(name).uplift ? classUp(cls) : cls }

// ceiling(depth) -> { agents, cycles } (A30); ceilingHit is true when `used` units reach the
// ceiling, so the next unit may not start: the stage ends and writes the gap.
function ceiling(depth) {
  const c = CLASSES.ceilings[depth]
  if (!c) throw new Error(`unknown depth ${depth}`)
  return c
}
function ceilingHit(depth, kind, used) {
  const c = ceiling(depth)
  if (!Object.prototype.hasOwnProperty.call(c, kind)) throw new Error(`unknown ceiling ${kind}`)
  const n = Number(used)
  // a NaN would compare false and let the ceiling pass unnoticed: a bad counter is an error.
  if (!Number.isFinite(n)) throw new Error(`ceilingHit needs a number of ${kind}, got ${used}`)
  return n >= c[kind]
}

// isBlocked / lastLine: the return shape every tool-set agent keeps. Every agent file puts the
// blocked word on the LAST line, so only that line counts: a return quoting the word mid-text
// (a finding, a file path, an error string) is a normal return, not a blocked stage.
function lastLine(ret) { return String(ret == null ? '' : ret).trim().split('\n').pop() }
function isBlocked(ret) { return ret == null || /^BLOCKED:/.test(lastLine(ret).trim()) }

// blockedLine(why): the blocked value of a stage, carrying the block word exactly once. Reasons
// come from two sources: an agent return that already opens with the word, and a reason this block
// wrote itself; prefixing both would print the word twice.
function blockedLine(why) {
  const w = String(why == null ? '' : why).trim() || 'no reason'
  return /^BLOCKED:/.test(w) ? w : `BLOCKED: ${w}`
}

// mustExist(ret, out): the output check of every stage that names an output file. A workflow
// script has no file access, so the agent's own return is the evidence: it names the path it
// wrote. Returns { ok, out, reason }; a false ok stops the flow instead of feeding the next stage.
function mustExist(ret, out) {
  if (!out) throw new Error('mustExist needs the output path')
  const s = String(ret == null ? '' : ret)
  // the agent's own last line is the reason, unprefixed here: blockedLine puts the word on once
  if (isBlocked(ret)) return { ok: false, out, reason: lastLine(s) || 'no return' }
  if (s.indexOf(out) === -1) return { ok: false, out, reason: `return does not name ${out}` }
  return { ok: true, out }
}

// outVerdict(ret, out): the whole verdict of a stage that names an output file — mustExist plus
// the size the agent reports. A script has no file access, so that number is the only evidence the
// file is not empty: a missing or zero count is an empty output, and an empty output is blocked,
// never done. The count counts only on a line naming the output path, and only on the FIRST such
// line, the demanded one: a later line naming the path with a byte count (a quoted run log, a
// check output, another file) must not decide the stage.
function outVerdict(ret, out) {
  const m = mustExist(ret, out)
  if (!m.ok) return { ok: false, out, bytes: 0, reason: m.reason, blocked: blockedLine(m.reason) }
  const RE = /(\d[\d,]*) *bytes\b/
  const line = String(ret).split('\n').filter(l => l.indexOf(out) !== -1 && RE.test(l))[0] || ''
  const n = Number(((line.match(RE) || [])[1] || '').replace(/,/g, ''))
  if (!(n > 0)) {
    const why = `return reports no non-empty ${out}: no positive byte count on a line naming it`
    return { ok: false, out, bytes: 0, reason: why, blocked: blockedLine(why) }
  }
  return { ok: true, out, bytes: n }
}

// ---- the review chain of idea 3.6 ----
// Every decision of the chain lives here as a pure function over the returns of its stages, so a
// test executes it instead of grepping workflows/chain.js. A workflow script has no file access:
// the hint lists and the evidence answers reach the script only as lines of an agent return, which
// is why the two parsers below are part of the chain and not of the prompt.

const HINT_CAP = 5 // A27: at most 5 hints per critic, so N critics give at most 5 x N hints
const SEVERITY_ORDER = ['low', 'medium', 'high']
const EVIDENCE_VERDICTS = ['confirmed', 'refuted', 'undetermined', 'harness']

// placeOf(place): "file:12-30", "file:12" or "doc.md#Section"; anything else is the whole file.
function placeOf(place) {
  const s = String(place == null ? '' : place).trim()
  const hash = s.indexOf('#')
  if (hash !== -1) {
    return { file: s.slice(0, hash).trim(), section: s.slice(hash + 1).trim(), from: null, to: null }
  }
  const m = s.match(/^(.*?):(\d+)(?:\s*-\s*(\d+))?$/)
  if (m) return { file: m[1].trim(), section: null, from: Number(m[2]), to: Number(m[3] || m[2]) }
  return { file: s, section: null, from: null, to: null }
}

// placeText(p): the place of a group, written back in the form the critics use.
function placeText(p) {
  if (p.section) return `${p.file}#${p.section}`
  if (p.from == null) return p.file
  return `${p.file}:${p.from}-${p.to}`
}

// parseHints(text, aspect): the hint lines of one critic return. Format, one line per hint:
//   HINT | <aspect> | <place> | <severity> | <suspected error> | <evidence that would settle it>
// Everything else in the return is prose and is ignored; a hint with no place could not be
// grouped and could not be settled, so it is no hint.
function parseHints(text, aspect) {
  const hints = []
  for (const line of String(text == null ? '' : text).split('\n')) {
    const parts = line.split('|')
    if (parts[0].trim() !== 'HINT') continue
    const f = parts.slice(1).map(s => s.trim())
    const place = f[1] || ''
    if (!place) continue
    const sev = (f[2] || '').toLowerCase()
    hints.push({
      aspect: f[0] || aspect || '',
      place,
      ...placeOf(place),
      // an unreadable severity counts as medium: it must not silently become the highest one and
      // pull the whole run into the long form
      severity: SEVERITY_ORDER.includes(sev) ? sev : 'medium',
      what: f[3] || '',
      evidence: f.slice(4).join(' | '),
    })
  }
  return hints
}

// capHints(hints, cap): the cap of A27, applied per critic. The critic writes the strongest first,
// so the cap keeps the head of its list.
function capHints(hintList, cap) {
  const n = Number(cap == null ? HINT_CAP : cap)
  if (!Number.isFinite(n) || n < 1) throw new Error(`capHints needs a positive cap, got ${cap}`)
  const hints = hintList || []
  return hints.slice(0, n)
}

// hintsOverlap(a, b): same place. Two line ranges overlap when they intersect; a hint on a whole
// file covers every hint in that file; a document section meets only the same section.
function hintsOverlap(a, b) {
  if (a.file !== b.file) return false
  if (a.section || b.section) return a.section === b.section
  if (a.from == null || b.from == null) return true
  return a.from <= b.to && b.from <= a.to
}

function higher(x, y) {
  return SEVERITY_ORDER.indexOf(x) >= SEVERITY_ORDER.indexOf(y) ? x : y
}

function joinInto(g, h) {
  g.from = g.from == null || h.from == null ? null : Math.min(g.from, h.from)
  g.to = g.from == null || h.to == null ? null : Math.max(g.to, h.to)
  g.severity = higher(g.severity, h.severity)
  for (const a of h.aspects || [h.aspect]) if (a && !g.aspects.includes(a)) g.aspects.push(a)
  g.hints = g.hints.concat(h.hints || [h])
  g.place = placeText(g)
  return g
}

// groupHints(hints): the merge and dedupe of 3.6, in the script and with no extra agent. Hints on
// the same or overlapping place form one group that keeps all its aspect tags and the highest
// severity of its members, so two critics pointing at the same lines cost one evidence run, not
// two. Same-meaning hints on different places stay separate.
function groupHints(hints) {
  const groups = []
  for (const h of hints || []) {
    const hit = groups.filter(g => hintsOverlap(g, h))
    if (!hit.length) {
      groups.push({
        file: h.file, section: h.section, from: h.from, to: h.to, place: h.place,
        severity: h.severity, aspects: h.aspect ? [h.aspect] : [], hints: [h],
      })
      continue
    }
    const g = joinInto(hit[0], h)
    // a later hint can bridge two groups that did not meet before: they become one
    for (const other of hit.slice(1)) {
      joinInto(g, other)
      groups.splice(groups.indexOf(other), 1)
    }
  }
  // every hint carries an id of its own inside its group (`g1.h2`). A group is one evidence run,
  // but the answers are per hint: a group holding a confirmed hint and a refuted one must not
  // carry the refuted one to the fixer under the group's verdict (A28).
  return groups.map((g, i) => {
    const id = `g${i + 1}`
    return {
      ...g, aspects: g.aspects.slice().sort(), id,
      hints: (g.hints || []).map((h, j) => ({ ...h, id: `${id}.h${j + 1}` })),
    }
  })
}

// maxSeverity(groups): the severity of the whole critique, the second input of the form choice.
function maxSeverity(groups) {
  let top = null
  for (const g of groups || []) top = top == null ? g.severity : higher(top, g.severity)
  return top
}

// chainForm(depth, maxSeverity): idea decision 5. The long form (one evidence researcher per
// group, then a separate triage) for `full` and for any hint group of high severity; the short
// form (one agent that collects and decides in one pass) otherwise.
function chainForm(depth, sev) {
  if (!CLASSES.ceilings[depth]) throw new Error(`unknown depth ${depth}`)
  return depth === 'full' || sev === 'high' ? 'long' : 'short'
}

// pickAspects(names, catalog): the `aspects` argument against the static catalog. It selects
// paragraphs and carries no prompt text; an unknown name is returned to the launcher, and the
// workflow stops instead of running a critic with no aspect paragraph.
function pickAspects(names, catalog) {
  const known = Array.isArray(catalog) ? catalog.slice() : Object.keys(catalog || {})
  const given = (names || []).slice()
  return { names: given, unknown: given.filter(n => !known.includes(n)), known }
}

// criticSplit(depth, names): one merged critic at `lite` and whenever a single aspect is asked
// for; one critic per aspect above that (3.6, A5). The split also decides the slot: a split
// critic sits one slot down, through roleSlot(name, size, split).
function criticSplit(depth, names) {
  if (!CLASSES.ceilings[depth]) throw new Error(`unknown depth ${depth}`)
  const list = (names || []).slice()
  if (depth === 'lite' || list.length < 2) return [list]
  return list.map(n => [n])
}

// parseEvidence(text): the answer lines of an evidence stage. Format, one line per hint group:
//   EVIDENCE | <group id> | confirmed|refuted|undetermined|harness | base:yes|base:no | <pointer>
// An unreadable verdict counts as undetermined: it then goes to the user and never to the fixer.
function parseEvidence(text) {
  const answers = []
  for (const line of String(text == null ? '' : text).split('\n')) {
    const parts = line.split('|')
    if (parts[0].trim() !== 'EVIDENCE') continue
    const f = parts.slice(1).map(s => s.trim())
    // the id of an answer is a hint id (`g1.h2`); the group it belongs to is its head
    const id = f[0] || ''
    if (!id) continue
    const group = id.split('.')[0]
    const v = (f[1] || '').toLowerCase()
    let verdict = EVIDENCE_VERDICTS.includes(v) ? v : 'undetermined'
    const base = (f[2] || '').trim()
    // a missing or unreadable control-run field settles nothing: reading it as `base:no` would
    // turn an answer nobody controlled into a finding of this change. It goes to the user, the
    // same way an unreadable verdict does. A harness failure needs no control run.
    if (verdict !== 'harness' && !/^base:\s*(yes|no)$/i.test(base)) verdict = 'undetermined'
    answers.push({
      id,
      group,
      verdict,
      kind: verdict === 'harness' ? 'harness' : 'object',
      onBase: /^base:\s*yes$/i.test(base),
      pointer: f.slice(3).join(' | '),
    })
  }
  return answers
}

// splitFailures(answers): the two rules of 3.6 that keep a finding honest. A failure of our own
// harness (tool, access, sandbox) is no finding about the object and is kept in its own list; a
// failure that also reproduces on the base version is no finding of this change either.
// Only a settled answer can be closed by the control run: an `undetermined` row with `base:yes`
// was settled by nobody, so it stays among the findings, reaches the undetermined list and the
// user (A28), and is never closed as "no finding of this change".
// dedupeAnswers(answers): one answer per hint. A stage that wrote two lines for one hint would
// otherwise put that hint in two lists at once — confirmed to the fixer and undetermined to
// the user. The stronger evidence wins: a settled verdict beats an unsettled one and beats a
// failure of our own harness; two settled verdicts that contradict each other (confirmed and
// refuted) settle nothing, so the hint goes to the user as undetermined.
const ANSWER_RANK = ['harness', 'undetermined', 'refuted', 'confirmed']
function dedupeAnswers(answers) {
  const out = []
  for (const a of answers || []) {
    const cur = out.filter(x => x.id === a.id)[0]
    if (!cur) { out.push({ ...a }); continue }
    const settled = v => v === 'confirmed' || v === 'refuted'
    const i = out.indexOf(cur)
    if (settled(cur.verdict) && settled(a.verdict) && cur.verdict !== a.verdict) {
      out[i] = { ...cur, verdict: 'undetermined', kind: 'object', pointer: `${cur.pointer} ;; ${a.pointer}` }
    } else if (ANSWER_RANK.indexOf(a.verdict) > ANSWER_RANK.indexOf(cur.verdict)) {
      out[i] = { ...a }
    }
  }
  return out
}

function splitFailures(answers) {
  const all = dedupeAnswers(answers)
  const harness = all.filter(a => a.kind === 'harness')
  const rest = all.filter(a => a.kind !== 'harness')
  const closed = a => a.onBase && a.verdict !== 'undetermined'
  const onBase = rest.filter(a => closed(a))
  const findings = rest.filter(a => !closed(a))
  return { findings, harness, onBase }
}

// hintRows(groups, answers): every hint of every group that ran, bound to the answer that settled
// it. The binding lives here and nowhere else, so the fixer's mandate, the review file and the
// return read the same rows and can no longer tell two different stories (A28).
// An answer names a hint id (`g1.h2`). A group of one hint is that hint, so an answer naming the
// group settles it; a group of several hints is not — one verdict over several hints would carry
// the refuted and the unsettled hints to the fixer under the confirmed one. A hint no answer
// names is unanswered: nothing settled it, so it is undetermined, never confirmed.
function hintRows(groups, answers) {
  const all = dedupeAnswers(answers)
  const kindOf = a => a.kind === 'harness'
    ? 'harness'
    : (a.onBase && a.verdict !== 'undetermined' ? 'onBase' : 'finding')
  const rows = []
  for (const g of groups || []) {
    const hints = (g.hints || []).length ? g.hints : [{ id: g.id, place: g.place, what: '' }]
    for (const h of hints) {
      const byHint = all.filter(x => x.id === h.id)[0]
      const byGroup = hints.length === 1 ? all.filter(x => x.id === g.id)[0] : null
      const a = byHint || byGroup || null
      rows.push({
        id: h.id, group: g.id, place: h.place || g.place, what: h.what || '',
        answered: !!a, verdict: a ? a.verdict : 'undetermined',
        kind: a ? kindOf(a) : 'finding', pointer: a ? a.pointer : '',
      })
    }
  }
  return rows
}

// chainRows(groups, answers): the one table of a chain run. The result file the judge writes and
// the return the caller reads are both this table — the open rows above all (A28), so a run can
// no longer return `undetermined: []` while its review file holds unsettled rows.
function chainRows(groups, answers) {
  const rows = hintRows(groups, answers)
  const findings = rows.filter(r => r.kind === 'finding')
  const undetermined = findings.filter(r => r.answered && r.verdict === 'undetermined')
  const unanswered = findings.filter(r => !r.answered)
  return {
    rows,
    findings,
    confirmed: findings.filter(r => r.verdict === 'confirmed'),
    rejected: findings.filter(r => r.verdict === 'refuted'),
    undetermined,
    unanswered,
    open: undetermined.concat(unanswered),
    harness: rows.filter(r => r.kind === 'harness'),
    onBase: rows.filter(r => r.kind === 'onBase'),
  }
}

// openRowsText(rows): the unsettled section of the review file, rendered from the rows the return
// carries. The judge copies this block instead of composing a list of its own.
function openRowsText(rows) {
  const open = (rows && rows.open) || []
  if (!open.length) return '(none)'
  return open.map(r => `| ${r.id} | ${r.place} | ${r.answered ? r.pointer || 'the facts settle nothing' : 'the evidence run came back with no readable answer for this hint'} |`).join('\n')
}

// fixerInput(groups, answers): what may reach the one who changes the object. A hint without
// evidence changes nothing, so a group goes on with its confirmed hints only; refuted,
// undetermined, harness, base-version and unanswered hints all stay out (A28).
function fixerInput(groups, answers) {
  const ok = chainRows(groups, answers).confirmed.map(r => r.id)
  const out = []
  for (const g of groups || []) {
    const hints = (g.hints || []).filter(h => ok.includes(h.id))
    if (hints.length) { out.push({ ...g, hints }); continue }
    // a group that carries no hint list of its own is addressed by its group id
    if (!(g.hints || []).length && ok.includes(g.id)) out.push(g)
  }
  return out
}

// confirmedOf(groups, answers): the hints a fact confirmed. The `confirmed` count of the result
// and of the status is this one, never the count that reached the fixer: a run whose triage or fix
// stage blocked still confirmed what it confirmed, and a judge that rejected a confirmed hint does
// not unmake the fact (A28). What the fixer got is its own number.
function confirmedOf(groups, answers) {
  return chainRows(groups, answers).confirmed
}

// undeterminedOf(groups, answers): the list that goes into the result file and into the status,
// for the main session to put to the user (A28: a script has no place for the user).
function undeterminedOf(groups, answers) {
  return chainRows(groups, answers).undetermined
}

// unansweredOf(groups, answers): a hint that ran and came back with no readable answer line.
// Nothing settled it, so it is neither confirmed nor rejected: it goes to the user with the
// undetermined ones (A28). Counting it out of existence would drop a whole hint.
function unansweredOf(groups, answers) {
  return chainRows(groups, answers).unanswered
}

// parseAccepted(text): the accepted rows of the judge's return. Format, one line per row:
//   ACCEPTED | <hint id> | <the change in one sentence>
// The whole decision stands in the judge's result file; these lines are the part a script without
// file access can read, and they are the only mandate the fixer gets.
function parseAccepted(text) {
  const rows = []
  for (const line of String(text == null ? '' : text).split('\n')) {
    const parts = line.split('|')
    if (parts[0].trim() !== 'ACCEPTED') continue
    const f = parts.slice(1).map(s => s.trim())
    if (!f[0]) continue
    rows.push({ id: f[0], group: f[0].split('.')[0], change: f.slice(1).join(' | ') })
  }
  return rows
}

// judgedInput(groups, answers, rows): the fixer's mandate in the long form. The judge decides
// which hints become changes, so a hint it rejected or left unsettled never reaches the fixer;
// it cannot widen the mandate either, so a row no fact confirmed stays out (A28). No accepted
// row, no fix stage.
function judgedInput(groups, answers, rows) {
  const ids = (rows || []).map(r => r.id)
  const out = []
  for (const g of fixerInput(groups, answers)) {
    const hints = (g.hints || []).filter(h => ids.includes(h.id))
    if (hints.length) { out.push({ ...g, hints }); continue }
    if (!(g.hints || []).length && ids.includes(g.id)) out.push(g)
  }
  return out
}

// chainSeats(depth, wanted): the ceiling of A30 is a ceiling per stage — at most `agents` units
// in one stage. What does not fit never starts: the stage ends and the rest becomes the gap of
// the result, never a second round. `seats` is what starts, `gap` what never does: a caller needs
// no third number, so none is returned.
function chainSeats(depth, wanted) {
  const room = ceiling(depth).agents
  const n = Number(wanted)
  if (!Number.isFinite(n) || n < 0) throw new Error(`chainSeats needs a unit count, got ${wanted}`)
  const seats = Math.min(n, room)
  return { room, seats, gap: n - seats }
}

// aspectsOrStop(names, catalog): the gate of the `aspects` argument. An unknown name selects no
// paragraph, so the critic would run with no question at all: the run stops and the catalog goes
// back to the launcher (3.6). An empty list is no review either.
function aspectsOrStop(names, catalog) {
  const p = pickAspects(names, catalog)
  if (!p.names.length) {
    return { ok: false, known: p.known, why: blockedLine('args.aspects must name at least one catalog aspect') }
  }
  if (p.unknown.length) {
    return { ok: false, known: p.known, why: blockedLine(`unknown aspect ${p.unknown.join(' ')}`) }
  }
  return { ok: true, known: p.known, names: p.names, why: null }
}

// chainPlan(depth, names, catalog): the whole plan of the critic stage as one decision — the gate
// of the `aspects` argument, the split into critic sets (A5) and the ceiling of A30 over them.
// `ok:false` stops the run before any agent starts and hands `why` and the catalog back to the
// launcher; `sets` are the critics that start, `gap` the ones the ceiling left out (never a second
// round), and `split` is the slot flag: a split critic sits one slot down.
function chainPlan(depth, names, catalog) {
  const gate = aspectsOrStop(names, catalog)
  if (!gate.ok) return { ok: false, known: gate.known, why: gate.why, sets: [], gap: [], room: 0, split: false }
  const all = criticSplit(depth, gate.names)
  const seats = chainSeats(depth, all.length)
  return {
    ok: true, known: gate.known, why: null,
    sets: all.slice(0, seats.seats), gap: all.slice(seats.seats),
    room: seats.room, split: all.length > 1,
  }
}

// chainEvidenceRuns(depth, form, groups): the groups the evidence stage really starts, the highest
// severity first, and the groups the ceiling of A30 left as the gap. The short form is one agent
// for every group, so it cuts nothing; the long form is one agent per group and takes the seats.
function chainEvidenceRuns(depth, form, groups) {
  const ordered = (groups || []).slice()
    .sort((a, b) => SEVERITY_ORDER.indexOf(b.severity) - SEVERITY_ORDER.indexOf(a.severity))
  if (form !== 'long') return { room: ceiling(depth).agents, ran: ordered, gap: [] }
  const seats = chainSeats(depth, ordered.length)
  return { room: seats.room, ran: ordered.slice(0, seats.seats), gap: ordered.slice(seats.seats) }
}

// chainStatus(s): the status sentence of one chain run, the one place that states the A28
// contract — the open rows go to the user, and the chain ran one round.
function chainStatus(s) {
  const o = s || {}
  const open = Number(o.undetermined || 0) + Number(o.unanswered || 0)
  const where = o.out || 'the result file'
  const openText = open
    ? `The ${open} open row(s) stand in ${where} and in this return: put them to the user, one decision each, before anything else is changed.`
    : 'Nothing is open for the user.'
  const gap = Number(o.gap || 0)
  const gapText = gap
    ? ` ${gap} unit(s) never started: the ceiling of ${Number(o.room || 0)} agents per stage ended the stage.`
    : ''
  // two numbers, never one: `confirmed` counts the facts, `to the fixer` counts the groups the
  // fix stage really got. A blocked triage reports the facts it has and 0 to the fixer.
  return `${o.form} form, ${Number(o.groups || 0)} hint group(s), ${Number(o.confirmed || 0)} confirmed, ${Number(o.fixing || 0)} to the fixer, ${open} open. ${openText}${gapText} One round only: a second critique needs the user's word.`
}

// chainResult(s): the whole return of one chain run, built in one place, so a stage that blocks
// late returns what the run already knows instead of a bare blocked line: the undetermined rows,
// the groups nobody answered, the harness failures in their own list, the failures that reproduce
// on the base version (named), the evidence files written, the gap and the status sentence (A28).
// `groups` is every group of the run, `ran` the groups a stage really started.
function chainResult(s) {
  const o = s || {}
  const groups = o.groups || []
  const answers = o.answers || []
  // one table for the whole run: the return and the review file are rendered from these same rows
  const T = chainRows(o.ran || groups, answers)
  // the facts are counted from the answers themselves, so no caller can claim a confirmation the
  // evidence never gave, and a stage that blocked late still reports what was confirmed
  const conf = T.confirmed
  const und = T.undetermined
  const open = T.unanswered
  const base = o.base || 'the base version'
  const res = {
    out: o.out == null ? null : o.out,
    form: o.form,
    aspects: o.aspects || [],
    critics: Number(o.critics || 0),
    groups: groups.length,
    confirmed: conf.length,
    fixing: Number(o.fixing || 0),
    fixed: o.fixed || 'no accepted row: nothing was changed',
    undetermined: und.map(r => `${r.id}: ${r.place} — ${r.pointer}`),
    unanswered: open.map(r => `${r.id} at ${r.place}: the stage ran and came back with no readable answer`),
    harness: T.harness.map(r => `${r.id}: ${r.pointer}`),
    onBase: T.onBase.map(r => `${r.id}: reproduces on ${base}, no finding of this change`),
    evidence: o.evidence || [],
    gap: o.gap || [],
    blockedStages: o.blockedStages || [],
    status: chainStatus({
      form: o.form, groups: groups.length, confirmed: conf.length, fixing: Number(o.fixing || 0),
      undetermined: und.length, unanswered: open.length, out: o.out,
      gap: Number(o.gapCount || 0), room: Number(o.room || 0),
    }),
  }
  if (o.stage) res.stage = o.stage
  if (o.blocked) res.blocked = blockedLine(o.blocked)
  return res
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    CLASSES, MODEL_NAME, EFFORT_NAME, submodes, cellFor, optsFor, classUp, slotForSize, bindClass,
    roleOf, roleNames, roleAgent, roleSlot, roleClass, ceiling, ceilingHit, isBlocked, lastLine,
    blockedLine, mustExist, outVerdict,
    HINT_CAP, SEVERITY_ORDER, placeOf, placeText, parseHints, capHints, hintsOverlap, groupHints,
    maxSeverity, chainForm, pickAspects, criticSplit, parseEvidence, dedupeAnswers, splitFailures,
    hintRows, chainRows, openRowsText,
    fixerInput, confirmedOf, undeterminedOf, unansweredOf, parseAccepted, judgedInput, chainSeats,
    aspectsOrStop, chainPlan, chainEvidenceRuns, chainStatus, chainResult,
  }
}
// ---- end shared block ----

// ---- roles (generated by bin/build.sh from lib/roles/*.md; never edit here) ----
const ROLE_TEXT = {
  "plan-author": "Plan author. You write one implementation plan for the task below, from the inputs only. A plan is checked by reading, so it must be complete enough to be executed by someone who has not read this conversation.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nRead every input first. Where the inputs contradict each other or leave a decision open, say so in the plan instead of choosing silently: an open point is a row of its own with the options and what each one costs.\n\nWrite one file, `{out}`, and nothing else. It holds: the goal in one paragraph; the parts, in dependency order, each with what it creates, changes and deletes; per part the acceptance condition and the executable check that proves it; the assumptions you had to make and what changes if one is wrong; the unknowns that block a part and how each is answered. No step whose result nobody can check.\n\nNever change a file of the repository, never run the plan, never invent a fact that no input carries.\n\nReturn: the output path, the part count, the open points, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "spec-author": "Specification author. You turn the intent and the subtasks below into requirements, invariants and constraints. The level above you is the intent: every line you write is checked against it, never against a memory of a conversation you did not see.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nWrite one file, `{out}`, and nothing else. It holds: functional requirements, each traceable to a named subtask; non-functional requirements, each in a measurable form (a number, a limit, a command that decides it) \u2014 a requirement nobody can measure is a requirement nobody can check, so either make it measurable or drop it; invariants that must hold after every change; constraints the solution may not break; and the open points where the intent does not answer the question.\n\nNothing outside the goal: a requirement with no subtask above it is either a missed subtask (say so) or scope you must not add.\n\nNever change a file of the repository, never write a second file.\n\nReturn: the output path, the counts (requirements, invariants, constraints, open points), then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "scenario-author": "Scenario author. You write the wanted behavior as text scenarios, before any test exists. The specification is the level above you: every requirement, invariant and constraint it carries needs at least one scenario, negative ones included.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nWrite one file, `{out}`, and nothing else. Pick the scenario form yourself \u2014 Gherkin, EARS, plain one-liners or any other \u2014 and keep one form through the file. Each scenario names the starting state, the action and the decisive observable result. Give no scenario an id, and never number them for a later test name to quote: coverage is checked by reading the two lists, and an id link between two texts drifts apart as soon as one of them changes.\n\nCover the negatives: what must not happen, what must fail, what must stay untouched. End the file with the requirements you found no scenario for, and why.\n\nNever write a test, never change a file of the repository.\n\nReturn: the output path, the scenario count, the uncovered requirements, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "code-author": "Code author. The tests already state what the change must do. You change the code until they pass, and nothing else.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nRead the inputs first, then change only the files the task names. Run the check the task names after every step; when the task names no check, say so in your return instead of inventing one. A test you cannot make pass is a finding: report it with the failing line verbatim, never weaken the test, never mark it skipped, never rewrite it to match the code.\n\nSmallest change that passes: no refactor the task did not ask for, no new abstraction for one caller, no new file where an edit was asked, no commit, no push.\n\nList every changed path in `{out}`, one per line, and write nothing else into it.\n\nReturn: the changed paths, the decisive line of the last check run verbatim, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "test-author": "Test author. You turn the scenario list into executable tests. The scenarios are the level above you: every scenario gets a test, and no test stands without a scenario.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nRead the scenario file first. Write the tests in the harness the repository already uses, with the assertions the scenario states and the decisive value in the failure message. Name a test after what it proves, never after a scenario id or number. A scenario you cannot express as a test is reported, not silently dropped.\n\nWrite the tests so they fail before the change and pass after it: a test that passes against the unchanged code proves nothing. Run them, and report the failure you see now as evidence that they bite.\n\nNever change the code under test, never relax an assertion to make a run green.\n\nList every test file you wrote in `{out}`, one path per line, and write nothing else into it.\n\nReturn: the test paths, the test count, the scenarios you could not express, the decisive line of the run verbatim, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "coverage-checker": "Coverage checker. You read two lists \u2014 the wanted scenarios and the tests that exist \u2014 and report where they do not meet. You judge no quality: a badly written test that covers its scenario is covered.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nMatch by meaning, by reading both lists. There is no id link between them and you must not propose one: a scenario id inside a test name drifts apart from the scenario as soon as one of the two changes.\n\nWrite one file, `{out}`: scenarios with no test, each with the scenario text; tests with no scenario, each with its path and name, split into \"the scenario list is missing it\" and \"the test proves nothing anybody asked for\"; and the pairs where the test covers only part of its scenario, with the part left out.\n\nNever write a test, never change a file under test.\n\nReturn: the output path, the three counts, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "critic": "Critic. You read the object below in a clean context and point at the places where an error may hide. You give hints, never verdicts: what you suspect is settled later by facts, not by your confidence.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nTool-call budget: at most 12 calls, and no call that changes anything. Read the object, then stop reading and write. Spending the budget on a wide tour costs more than it finds; read what the task points at.\n\nAt most 5 hints, the strongest first. Every hint carries: the aspect it comes from; the place (file and line range, or document section); the error you suspect, in one sentence; the severity (high, medium, low); and the one piece of evidence that would settle it \u2014 a command to run, a file to read, a value to compare. A hint nobody could settle is not a hint, drop it.\n\nNo praise, no summary of what the object does, no style remark, no restatement of a rule the object already follows. When the task names a version from before the change, a shape that already stands in it is no finding of this change: hint at what this change brought.\n\nWrite the hint list into `{out}` in that shape and change nothing else.\n\nReturn: the output path, the hint count by severity, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "evidence-researcher": "Evidence researcher. One group of hints, many cheap queries, one answer per hint: confirmed, refuted or undetermined. You decide nothing about what to change; you bring the facts that decide it.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nFor every hint of the group, one answer under that hint's own id: run the check the hint names, read the code path around the place, and reproduce the failure when the hint claims one. A failure, or a shape, that already stands in the unchanged base version is not a finding of this change \u2014 say so, with both runs or both places quoted.\n\nAnswer each hint with `confirmed`, `refuted` or `undetermined`, every answer carrying its pointer: file and line, command and its decisive output line, or commit hash. `confirmed` needs a fact of the object that holds this one hint up; a hint the files and the runs neither hold up nor settle is `undetermined`, never `confirmed`, and no hint is confirmed for sounding right. `undetermined` is a real answer and better than a guess; it says what you tried and what would settle it.\n\nA hint that calls something needless, duplicated or absent is refuted as soon as a fact stands against it: a caller, a test, or a rule of the object's own documents that needs exactly that thing. Look for one before you confirm such a hint, and quote it with file and line.\n\nKeep two kinds of failure apart: a failure of the object under review, and a failure of your own run (a tool, an access, a sandbox limit). The second one is never a finding about the object; report it in its own list.\n\nWrite the answers into `{out}` and change nothing under review. You have no Write tool: create `{out}` with a shell redirect, and write no other file.\n\nReturn: the output path, the counts (confirmed, refuted, undetermined, harness failures), then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "evidence": "Evidence agent, short form: you collect the facts for the hints below and decide each one yourself, in one pass.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nPer hint, under that hint's own id: run the check it names, read the place it points at, then say `confirmed` (a fact of the object holds this one hint up and it names a real change), `refuted` (a fact settles it against the hint) or `undetermined` (the facts do not settle it, so it goes to the user). Every line carries its pointer: file and line, command with its decisive output line, or commit hash. A claim with no pointer does not go in, and a hint nothing holds up is `undetermined`, never `confirmed`.\n\nA hint that calls something needless, duplicated or absent is refuted as soon as a caller, a test or a rule of the object's own documents needs exactly that thing; look for one before you confirm such a hint.\n\nA failure, or a shape, that already stands in the unchanged base version is not a finding of this change. A failure of your own run \u2014 tool, access, sandbox \u2014 is `harness`, no finding about the object either; keep those in their own list.\n\nA confirmed hint states the change in one sentence: what to change and where. It never states how to write the code.\n\nYou have no Write tool: create `{out}` with a shell redirect, and write no other file. Write the same four words into `{out}`: confirmed with the change, refuted with the refuting fact, undetermined with what is missing, harness failures apart.\n\nReturn: the output path, the four counts, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "evidence-triage": "Triage. You are the judge of the review: you read the hints and the facts collected for them, and you decide which ones become changes. You run no query of your own \u2014 if a decision needs a fact nobody collected, that hint is unsettled, and unsettled goes to the user, never to the one who changes the object.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nPer hint, by its own id: accept it only when its own row of the fact list says `confirmed`; reject it when a fact refutes it, or when nothing but the hint itself speaks for it; mark it unsettled when the facts are inconclusive. A hint whose row says undetermined, a hint no row names at all, and a hint that is merely plausible are never accepted, however sound they read. Two hints of one group are two decisions: the verdict of one says nothing about the other. Severity is measured against the quality criteria named in the task, not against your taste.\n\nWrite `{out}`: the accepted list, each row with the hint id, the place, the required change in one sentence and the fact it rests on; the rejected list with the refuting fact; the unsettled list exactly as the task gives it \u2014 those rows are what the run returns to the user, so you copy them and add none of your own. Two hints about one place that need one change are one row, keeping both aspect tags and both ids.\n\nNever change the object, never add a finding nobody hinted at, never accept a hint because it sounds reasonable.\n\nReturn: the output path, the three counts, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "fixer": "Fixer. You change the object by the accepted list the task names, and by nothing else. That list is the whole mandate: an improvement nobody accepted is scope you may not add, and a row that stands in a file you read but not in the task's list is not yours to apply.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nPer accepted row: make the smallest change that satisfies it, at the place it names. A row you disagree with is not dropped and not reinterpreted \u2014 make the change and say in your return why you think it is wrong, or, when the change would break something the row did not see, stop at that row and report it with the evidence.\n\nAfter the changes run the check the task names and quote its decisive line. When the check fails after your change, fix your change; when it already failed before it, say so with both runs.\n\nNever touch a place no row names, never commit, never push.\n\nList every changed path in `{out}`, one per line, and write nothing else into it.\n\nReturn: the changed paths, the rows you could not apply, the decisive line of the check verbatim, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "researcher": "Fact researcher. One direction, facts with pointers, no opinion. Everything you write must be checkable by someone who reads the pointer.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nStart from the inputs, then search the repository and its history as the direction needs: read files, grep, git log, run a read-only command when it settles a question. Read only what the direction needs; a wide tour costs more than it finds. Change no file of the repository and run nothing that writes.\n\nWrite one bundle file, `{out}`: the direction in one line; the facts, each with its evidence pointer (file and line, command with its decisive output line, or commit hash); the unknowns you could not settle, each with what you tried and what would settle it; the facts that contradict each other, kept both with their pointers.\n\nA claim with no pointer does not go into the bundle. A guess belongs to the unknowns, never to the facts.\n\nReturn: the output path, the fact count, the unknown count, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "web-researcher": "Web researcher. One question, public sources, facts with their source. You have no repository access: everything you report comes from what you fetched, with the address it came from.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nSearch, then fetch the pages that carry the answer; prefer the primary source (official documentation, the project's own repository, a release note) over a retelling of it. Two independent sources for a fact that a decision rests on; when only one exists, say that.\n\nWrite one bundle file, `{out}`: the question; the facts, each with its URL and the date the page carries; the version or date the fact is true for, when the subject changes over time; contradictions between sources, kept with both addresses; what you could not find, and where you looked.\n\nNever present a memory as a fetched fact, never give an address you did not open.\n\nReturn: the output path, the fact count, the sources used, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "synthesizer": "Synthesis author. Several bundles of facts and one critique of them are below. You write the one answer they add up to, and you add no fact of your own.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nRead every bundle and the critique first. Where two bundles disagree, keep both claims with their pointers and say which one the evidence favours and why; where the critique withdraws a fact, drop it from the answer and name it under the open points.\n\nWrite one file, `{out}`: the answer to the question, each claim carrying the pointer it rests on; the facts grouped by subject, deduplicated, each with its pointer; the open unknowns, from the bundles and from the critique; the next step the evidence supports. Nothing you could not trace back to an input.\n\nNever open a source of your own, never soften a contradiction into a compromise sentence, never change a file of the repository.\n\nReturn: the output path, the claim count, the open unknowns, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "executor": "Executor. You run the check and report what it said. You do not repair, you do not interpret, you do not decide whether the result is acceptable.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nRun exactly the command the task names, from the directory it names. Every synchronous Bash call sets `timeout` at most 120000. A command that may run longer never runs synchronously: start it detached and let it write its own done-file, `(<cmd>; touch <done>) > <log> 2>&1 &`, then poll with one call per turn, `for i in $(seq 36); do test -f <done> && break; sleep 5; done; test -f <done> && echo done || echo wait`, until the done-file exists. Never end your turn with a job still running.\n\nWrite the raw output into `{out}` and keep it: it is the evidence, and nobody else keeps a copy. You have no Write tool: create `{out}` with a shell redirect, and write no other file.\n\nThe verdict is the exit status plus the summary line the run printed, never your reading of the log. A run that could not start (missing tool, denied access, no such directory) is not a FAIL of the object: report it as a harness failure.\n\nReturn: PASS or FAIL with the exit status, the summary line verbatim, the path of the raw output, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "waiter": "Waiter. Something is already running and somebody must sit with it. You wait, watch, and come back with the decisive facts \u2014 cheaply, without holding a rich context open.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nPoll, never busy-wait: one Bash call per turn, each with an explicit `timeout` at most 120000, sleeping in short steps between checks, `for i in $(seq 36); do <the condition> && break; sleep 5; done`. Stop at the first of: the condition the task names holds, the deadline it names passes, or the thing you watch dies. Never end your turn with a job still running in the background.\n\nWhile waiting, change nothing: no restart, no retry, no repair, no cleanup, unless the task states it in so many words.\n\nYou have no Write tool: create `{out}` with a shell redirect, and write no other file. Write what you observed into `{out}`: the moments you checked, what you saw at each, and the decisive lines verbatim.\n\nReturn: which of the three stop conditions ended the wait, how long it took, the decisive lines verbatim, then the last line `DONE` or `BLOCKED: <reason>`.\n",
  "translator": "Translator into Russian. One file in, one file out, same document in another language. You are not an editor: you shorten nothing, you add nothing, you fix nothing you think is wrong.\n\nInputs (absolute paths):\n{in}\n\nTask:\n{ask}\n\nRead the input once, write `{out}` once. Keep the markdown structure line for line: headings, lists, tables with their columns, code blocks, links, emphasis. Keep verbatim, untranslated: identifiers, file paths, commands, flags, code, numbers, product and tool names, and the text inside code spans and code blocks.\n\nNatural technical Russian, not a word-by-word rendering: the sentence that a Russian engineer would write for that meaning. Keep the register of the original \u2014 a terse line stays terse.\n\nEvery paragraph of the original has its paragraph in the translation. A part you could not render goes into the file in the original language and into your return, named by its heading; silently dropping it is the one unrecoverable error here.\n\nReturn: the output path, the sections left untranslated, then the last line `DONE` or `BLOCKED: <reason>`.\n",
}
// ---- end roles ----

// The five tool-set agents this catalog may launch. A role whose agent is not one of them is a
// defect of lib/classes.json, not a launch the main session may make: the list is literal, so a
// static test can compare it against the role map and against the agent files on disk.
const AGENTS = ['session:tools-edit', 'session:tools-read-bash', 'session:tools-read-write', 'session:tools-read-write-bash', 'session:tools-web']

let A = args || {}
if (typeof A === 'string') A = JSON.parse(A)
const ROLE = A.role
const OUT = A.out
const ASK = A.ask
const CLS = A.class || CLASSES.defaultClass
const SIZE = A.size || CLASSES.defaultSize
// a list argument passed as one string reaches the script as a string: it takes the error path
// below, never `.filter is not a function` inside the script
const IN = A.in == null ? [] : A.in
const SUBS = A.submodes == null ? [] : A.submodes

// Every argument error returns instead of throwing: the launcher gets the catalog back and can fix
// the call without reading this script. The blocked value opens with the word the standard parser
// looks for, so a failed role stage never reads as a normal return.
const fail = (why, extra) => ({ role: ROLE || null, blocked: blockedLine(why), ...(extra || {}) })

// The launch line is logged before the first argument check: a call that returns an argument error
// without logging leaves no line in /workflows and reads as a call that never happened.
log(`${[CLS, ...(Array.isArray(SUBS) ? SUBS : [])].join('-')}-role | role=${ROLE || '(none)'} size=${SIZE} in=${Array.isArray(IN) ? IN.length : '(no array)'} out=${OUT || '(none)'}`)

if (!ROLE) return fail('args.role is required', { roles: roleNames() })
if (!roleNames().includes(ROLE) || !ROLE_TEXT[ROLE]) return fail(`unknown role ${ROLE}`, { roles: roleNames() })
if (!ASK) return fail('args.ask (the job in prose) is required')
if (!OUT) return fail('args.out (one absolute output path) is required')
// a relative out would still match the agent's return, so the output check would pass over a file
// nobody can find: the contract says absolute, and the script holds the launcher to it
if (typeof OUT !== 'string' || OUT[0] !== '/') return fail(`args.out must be an absolute path, got ${OUT}`)
if (!CLASSES.table[CLS]) return fail(`unknown class ${CLS}`, { classes: Object.keys(CLASSES.table) })
if (!CLASSES.sizes.includes(SIZE)) return fail(`unknown size ${SIZE}`, { sizes: CLASSES.sizes })
if (!Array.isArray(IN)) return fail('args.in must be a JSON array of absolute paths')
if (!Array.isArray(SUBS)) return fail('args.submodes must be a JSON array', { submodes: CLASSES.submodeOrder })
const BADSUB = SUBS.filter(s => !CLASSES.submodeOrder.includes(s))
if (BADSUB.length) return fail(`unknown submode ${BADSUB.join(' ')}`, { submodes: CLASSES.submodeOrder })
if (SUBS.length === 3) return fail('all three submodes banned: nothing left to run on')

const AGENT = `session:${roleAgent(ROLE)}`
if (!AGENTS.includes(AGENT)) return fail(`role ${ROLE} names no tool-set agent: ${AGENT}`)
const SLOT = roleSlot(ROLE, SIZE)
const RUN = bindClass(CLS, SUBS)
// an output only a review could check gets a stronger author, one class step up (3.5 rule 2)
const JOB = bindClass(roleClass(ROLE, CLS), SUBS)

// The role text is a template over the uniform argument shape and nothing else: a placeholder
// outside {in} {ask} {out} would be a per-role argument the contract cannot state, so it stops the
// launch instead of reaching the agent as literal braces.
const FIELDS = { in: IN.length ? IN.join('\n') : '(none named)', ask: ASK, out: OUT }
const UNKNOWN = []
// the scan is case-aware: {OUT} or {Ask} is a placeholder nobody fills, so it stops the launch
// instead of reaching the agent as literal braces
const PROMPT = ROLE_TEXT[ROLE].replace(/\{([A-Za-z][A-Za-z0-9_-]*)\}/g, (m, k) => {
  if (!Object.prototype.hasOwnProperty.call(FIELDS, k)) { UNKNOWN.push(k); return m }
  return FIELDS[k]
})
if (UNKNOWN.length) return fail(`role text of ${ROLE} reads ${UNKNOWN.join(' ')}, outside the argument shape`)

const O = JOB.opts(SLOT, ROLE, { agentType: AGENT, phase: 'Role' })
log(`${RUN.name('role')} | role=${ROLE} class=${JOB.class} slot=${SLOT} label=${O.label} agent=${AGENT} size=${SIZE} in=${IN.length} out=${OUT}`)

phase('Role')
// How the agent gets the size: with Bash it counts the file, with Read but no Bash it reads the
// file it just wrote back and counts what it sees there, and the web agent (neither tool) can only
// state what it wrote. The three lists are literal, so they cannot drift from the agent files.
const BASH_AGENTS = ['session:tools-edit', 'session:tools-read-bash', 'session:tools-read-write-bash']
const READ_AGENTS = ['session:tools-read-write']
const COUNT = BASH_AGENTS.includes(AGENT) ? 'count it with `wc -c`'
  : READ_AGENTS.includes(AGENT) ? `you have no shell: read ${OUT} back with your Read tool after writing it and count what it holds, never a number from memory`
  : 'you have neither a shell nor a Read tool: state the number of characters you wrote'
// The size line comes first because a return that buries it, or forgets it, is a blocked stage
// here even when the file is on disk: the count is the only evidence this script can read.
const TAIL = `\n\nWork only inside the directories the paths above name. Write ${OUT} yourself. Start your return with one line \`${OUT} <n> bytes\` giving the size of what you wrote (${COUNT}), then the return the job above asks for. A file you did not write, or left empty, is not a finished job: return BLOCKED: <why> instead of a size. On a permission denial stop at once and return BLOCKED: <the denied action>.`
const r = await agent(PROMPT + TAIL, O)
// the stage is done only when the return names the output file and reports a positive size for it;
// a stage that wrote nothing, or an empty file, returns blocked, never done. The whole verdict is
// outVerdict() of the shared block, so a test can execute it instead of reading this line.
const V = outVerdict(r, OUT)
if (!V.ok) return { role: ROLE, out: OUT, class: JOB.class, slot: SLOT, label: O.label, blocked: V.blocked }
return { role: ROLE, out: OUT, class: JOB.class, slot: SLOT, label: O.label, agent: AGENT, bytes: V.bytes, result: lastLine(r) }
