// Build fixture: a script with the generated regions of bin/build.sh. Never loaded, only stamped.
// The test copies it to a temp dir; the copy in the repo stays with empty regions.
export const meta = { name: 'marker-fixture', description: 'Build fixture' }

// ---- shared block (generated by bin/build.sh from lib/block.src.js and lib/classes.json; a hand edit inside is lost) ----
// ---- end shared block ----

// ---- roles (generated by bin/build.sh from lib/roles/*.md; a hand edit inside is lost) ----
// ---- end roles ----

const TAIL = 'this line stays below every generated region'
