#!/bin/sh
# SessionStart hook: injects one part of the session base (base/BASE-<n>.md, generated by
# base/split.sh from base/BASE.md) into every session at startup, resume, compact and
# clear. One hook entry per part; each additionalContext stays under the 10,000-character
# limit above which Claude Code persists the output to a file instead of injecting it.
# Usage: base-session-start.sh <part number>
DIR=$(cd "$(dirname "$0")/.." && pwd)
PART="$DIR/base/BASE-${1:-1}.md"
[ -f "$PART" ] || exit 0
python3 - "$PART" <<'PY'
import json, sys
text = open(sys.argv[1], encoding='utf-8').read()
print(json.dumps({"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": text}}))
PY
exit 0
